### ISSUE TITLE
Objectgegevens- maar 1 telefoonnummer ingeven mogelijk

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/OIV_project#179]
Bij het invoeren van de objectgegevens kan maar 1 telefoonnummer ingegeven worden (ivm een max aantal characters) de behoefte is dat er meerdere telefoonnummers ingevoerd kunnen worden.

We draaien op OIV 3.3.5

**Comment by Oostjoost** [comment]
Gereed via databasescript aanpassing van 11 karakters naar 100 karakters. Zit in databasemigratiescript 3.3.5-3.3.6

**Comment by Oostjoost** [comment]
I.o.m. VRF opgelost, bewust niet gekozen voor een 1-n relatie
