### ISSUE TITLE
status "aanpassing" in Historie

### ISSUE THREAD

**Issue by vnogzwarta** [OIV-NL-QGIS/OIV_project#181]
Als je in tab Historie bij WAT "aanpassing" gebruikt blijft het bolletje met de i blauw in de management laag, allen door "update"of "nieuw" te gebruiken wordt het bolletje met de i groen. Is het juist gedacht dat de optie "aanpassing" dan geen meerwaarde heeft?

**Comment by Oostjoost** [comment]
De actualisatie termijn bepaalt de groen, blauwe, oranje of rode bolletjes. Om evengoed een "aanpassing" te registeren is bij WAT de optie aanpassing opgenomen. Alleen nieuw en update zorgen dus voor een verschuiving van de actualisatie termijn mits er met de matrix-codes wordt gewerkt.
