### ISSUE TITLE
Verwijderen bouwlaag geeft Python StopIteration error

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#183]
Bij het verwijderen van een bouwlaag verschijnt soms de volgende melding:

Er is een fout opgetreden bij het uitvoeren van Python code: 
```
StopIteration 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\oiv\bag_pand\oiv_pandgegevens.py", line 172, in run_delete
    ifeature = next(ilayer.getFeatures(request))
StopIteration

```
Python versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS versie: 3.16.5-Hannover Hannover, 58ba7c1ed6

**Comment by Oostjoost** [comment]
Ik heb alle next() vervangen in de code waarbij eerst een getFeatures wordt uitgevoerd en daarna gecontroleerd of er wel features zijn terug gekomen op de request. Indien dat zo is wordt pas next() uitgevoerd. Next() is de eerste feature die voldoet aan de request.
