### ISSUE TITLE
Printen van verschillende bouwlagen

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/OIV_project#186]
Je kunt in een layout niet verschillende bouwlagen presenteren. (Meerdere kaarten op 1 pagina)
Wanneer je van bouwlaag wijzigt veranderen alle kaartjes op de pagina naar die bouwlaag.
(De omweg is van elke bouwlaag een pagina maken)
 
Is het mogelijk om dit te automatiseren?

**Comment by Oostjoost** [comment]
TODO:

- [x] - Titel aanpassen
- [x] - Dieren true/false -> ja/nee
- [x] - Meldinging dat printen gereed is
