### ISSUE TITLE
Extra info toevoegen aan de kaart (bij printen)

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/OIV_project#187]
Wanneer je een Legenda wilt toevoegen aan de kaart krijg je niet de symbolen uit de plugin te zien.

ook zou de extra informatie (uit objectgegevens) op de pdf getoond moeten kunnen worden.

Is het mogelijk om dit te ontwikkelen?

**Comment by Oostjoost** [comment]
Legenda in QGIS is niet dynamisch op te bouwen aangezien de verwijzing naar de SVG symbolen uit de database komt en niet uit het QGIS project. Mijn inziens zijn er 2 mogelijkheden:

1. Een PNG/PDF maken waarin alle symbolen staan met de benaming, dus een statische legenda
2. Alle styling/verbeelding toch weer opnemen in QGIS, echter is hier juist bewust van afgestapt, aangezien je dan voor elk nieuw symbool het project moet aanpassen.

**Comment by Oostjoost** [comment]
Het wordt optie 1
PNG/PDF met legend wordt gemaakt door de werkgroep en verplaatst naar een aparte issue
