### ISSUE TITLE
Symbolen versie 3.3.6

### ISSUE THREAD

**Issue by vnogzwarta** [OIV-NL-QGIS/OIV_project#188]
Bij "terrein" in tabblad algemeen komt bij het plaatsen van het symbool afsluiter SVM het symbool schakelaar RWA
Bij tabblad "industrie" geeft blauwe sleutelkluis een vraagteken
Bij tabblad "bluswater" geeft het symbool rode kruis ook een vraagteken

**Comment by ghost** [comment]
Klein issue, pakt Joost mee.

**Comment by Oostjoost** [comment]
![afbeelding](https://user-images.githubusercontent.com/23038880/144057073-03cc6969-3e9a-473e-841f-f976cd1df049.png)
