### ISSUE TITLE
Gevaarlijke stof nummer wordt niet gekoppeld aan stofnaam

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/OIV_project#189]
Gevaarlijke stof nummer wordt niet gekoppeld aan stofnaam. 
Als je een gevi nummer invult met de plug-in zet QGIS geen stofnaam neer, en komt ie ook dus niet zichtbaar in MOI.
Dit zou toch automatisch moeten gebeuren vanuit de gevaarlijke stoffen naam DB?

**Comment by Oostjoost** [comment]
![afbeelding](https://user-images.githubusercontent.com/23038880/144087074-9042f5aa-9e28-4961-8068-32519d011bc0.png)
Dit zijn enige gegevens die bekend zijn in database...... dus geen stofnaam. Is ook nooit zo geweest.
