### ISSUE TITLE
Weg gooifunctie werkt niet

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/OIV_project#195]
Als je in een object contour lijnen aan het tekenen ben en je wil een lijn (deel) weg gooien werkt de afvalbak in de plugin niet, als je op de afvalbak in de boven balk klik dan werkt het wel.

**Comment by Oostjoost** [comment]
die werkt gewoon, niet duidelijk wat hiermee wordt bedoeld, aangezien ik gewoon alle contourlijnen kan weggooien.

**Comment by Joachim-Tempelaars** [comment]
Is fout van Bob
