### ISSUE TITLE
Slagbomen ook bouwlaag mee geven.

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/OIV_project#196]
Voor Parkeer kelders of verdiepingen is het handig dat de slagboom (voor een parkeer garage) een bouwlaag mee krijgt.

**Comment by Oostjoost** [comment]
@OIV-NL-QGIS het lijkt mij wel dat de slagboom in de tabel bereikbaarheid moet blijven staan? Houdt dit dan een wijziging in van het IMROI model? Bereikbaarheid zit namelijk gekoppeld aan een repressief object en niet aan een "pand".

Enige ander mogelijkheid zonder aanpassing aan IMROI is de slagboom opnemen in de lijnen laag op de bouwlaag, namelijk veiligheidsvoorziening bouwkundig. Klopt gevoelsmatig niet helemaal.

Graag even een oplossing aandragen voordat ik hiermee verder kan......

**Comment by OIV-NL-QGIS** [comment]
Joost graag aparte rood witte lijn (Slagboom) toevoegen (bouwkundige veiligheidsvoorzieningen) bij overige lijnen van Objecten met kolom bouwlaag er aan.

**Comment by Oostjoost** [comment]
![image](https://user-images.githubusercontent.com/23038880/149939410-edbf24e3-c060-4e6c-b14c-caecc73e7834.png)
