### ISSUE TITLE
Toevoegen info-of-interest: alternatieve bluswatervoorziening

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#202]
Heeft geen beschrijvend label bij een hover over het icoon, en is niet toe te voegen aan het terrein zelf. Betreft de testversie

**Comment by ghost** [comment]
Betreffen de twee nieuwe blauwe vlakken

**Comment by Oostjoost** [comment]
Helemaal correct, op dit moment zijn er nog geen vlakken "of-interest" toegevoegd. De 2 vlakken open water en zwembad hadden (nog) niet aan de te tekenen objecten moeten worden toegevoegd. Zijn dit ook objecten die moeten worden getekend los van een object of bouwlaag? Ze stonden namelijk niet in de lijst met objecten, vandaar dat ze er niet tussen staan. Eigenlijk zijn de "knoppen" onterecht in de GUI opgenomen.

**Comment by ghost** [comment]
Deze functionaliteit kwam niet bij ons vandaan, werd alleen tijdens het testen geconstateerd. Misschien kan @Joachim-Tempelaars of @OIV-NL-QGIS  hier inhoudelijk op in gaan?
