### ISSUE TITLE
Feedback release v3.3.9-beta1

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#217]
Paar dingen die bij het installeren spelen:

1) Database-configuratie hardcoded in project, waardoor PGSERVICE bestand niet altijd gebruikt wordt:
![lagen](https://user-images.githubusercontent.com/73171956/151758558-4efb33d1-0d18-473e-87c6-e0d7dc230f4a.png)

2) Fout bij hernoemen kolomnaam in database: https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.3.8-3.3.9.sql#L667
Origineel:
```
CREATE OR REPLACE VIEW objecten.object_bgt
AS SELECT b.id,
```
Aangepast, en werkt:
```
DROP VIEW objecten.object_bgt;
CREATE OR REPLACE VIEW objecten.object_bgt
AS SELECT b.id,
```

2) Syntax error https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.3.8-3.3.9.sql#L2209
```
    part.typeobject,
   FROM objecten.scenario_locatie o
```

3) Syntax error https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.3.8-3.3.9.sql#L2235
```
    ''::text AS applicatie,
   FROM objecten.scenario_locatie o
```

**Comment by Oostjoost** [comment]
1.  2 lagen (Scenario locatie en Settings) -> had in de qgs project file op sslmode==allow moeten worden gezet. Heb gelijk alle andere lagen nagelopen. De 2e laag had niet in het project mogen zitten, betreft een plugin configuratie laag, welke even tijdelijk voor de configuratie van de scenario's was toegevoegd aan het project. 
https://github.com/OIV-NL-QGIS/QGIS_project/commit/02c1edcf5d28313c3e9390335bf56c2bff07f98e

**Comment by Oostjoost** [comment]
2. - aanpassing overgenomen
3. - 2 komma's welke er niet hadden mogen staan
https://github.com/OIV-NL-QGIS/IMROI_database/commit/b1420c11ae1964db6cba3aa0a165013ff65253ce

**Comment by Oostjoost** [comment]
4. Nog een extra issue: Nieuwe objecten werden niet getoond als er geen historie was aangemaakt. De reden was een INNER JOIN wat een LEFT JOIN had moeten zijn.
https://github.com/OIV-NL-QGIS/IMROI_database/commit/b1420c11ae1964db6cba3aa0a165013ff65253ce

**Comment by Oostjoost** [comment]
Ik zal deze week op basis van de feedback tijdens het testen een nieuwe beta2 versie opleveren.
