### ISSUE TITLE
Sleutelbuis

### ISSUE THREAD

**Issue by Joachim-Tempelaars** [OIV-NL-QGIS/OIV_project#219]
Terrein, object tekenen, toetreding en sleutelbuis.
	Sleutelbuis	
		Geen object gevonden om aan te koppelen.
		Zorg dat het te koppelen object in het kaartbeeld zichtbaar is

Ook bij object, toetreding

**Comment by Oostjoost** [comment]
had je een ingang getekend en in beeld?

**Comment by Oostjoost** [comment]
Omdat we afgestap zijn van de nearest neighbour functie, wordt er niet meer gezocht naar het dichtsbijzijnde om aan te koppelen. En laat dit nu net bij sleutelbuis nog wel nodig zijn. Wordt aangepast.
