### ISSUE TITLE
Schrijffouten bij het installeren in de QGIS program files folder

### ISSUE THREAD

**Issue by Oostjoost** [OIV-NL-QGIS/OIV_project#230]
Installatie in QGIS appdata folder niet beter? Dat is ook waar de plugin vanuit QGIS repository wordt geinstalleerd

**Comment by ghost** [comment]
Ik zou dit graag even in het wekelijkse overleg bespreken. Heeft qua installatie en beheer nog wat haken en ogen. Lijkt me goed dit eerst even in gezamenlijkheid te bespreken morgenmiddag.

**Comment by ghost** [comment]
Zojuist besproken in het wekelijkse overleg. Conclusie daar is dat distributie via de plugin manager van QGIS niet wenselijk is. Releases worden netjes via GitHub uitgebracht openbaar, en vanaf daar kunnen de beheerders in hun regio de applicatie installeren. Systeem-brede installatie ipv per gebruiker. Om zelf in de lead te blijven m.b.t update proces bij gebruikers en installatie hiervan.

**Comment by Oostjoost** [comment]
- Op welke wijze voorkomen we de melding dat de installatie niet uitgevoerd kan worden door onvoldoende rechten? Dit lijkt namelijk het geval te zijn na een nieuwe installatie van QGIS.
- Moet ik de plugin van de QGIS repository afhalen?
- Is het een idee om de plugin uit de installer te halen en los te distribueren?

**Comment by Oostjoost** [comment]
Ik ga onderzoeken of de installer i.c.m. de registerverwijzing de oorzaak is van het niet willen installeren van de plugin in de program files folder.

**Comment by Oostjoost** [comment]
De installatie blijft op de manier vormgegeven zoals deze altijd al was

**Comment by Oostjoost** [comment]
Vanaf QGIS 3.22 is de installatie methode veranderd en wordt het installatie pad niet meer weggeschreven in het register, tenminste ik kan niet vinden waar dat zou moeten staan. Voor 3.16 kan ik prima de oude installatie maken, maar nog niet voor 3.22, dit vergt meer onderzoek.

**Comment by Oostjoost** [comment]
Om nu even een installatie uit te brengen, laat ik de 3.16 versie op de oude manier installeren en de 3.22 versie installeert in de 
AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins folder

**Comment by Oostjoost** [comment]
Daarnaast heb ik zoals afgesproken de plugin versie van de QGIS repository verwijderd
