### ISSUE TITLE
[Feedback v3.3.9_beta3] Verkeerde regio bij start applicatie

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#231]
QGIS toont de verkeerde regio bij de start van de applicatie. 
![b3-1](https://user-images.githubusercontent.com/73171956/154216343-dff57629-833e-4825-a17e-1929368a70c5.png)

Betreft versie: https://github.com/OIV-NL-QGIS/QGIS_project/releases/tag/v3.3.9_beta3

Als ik kijk naar dit bestand https://github.com/OIV-NL-QGIS/QGIS_project/blob/master/qgis_project/objecten/update_dimension_tables_proj.py#L222 haalt die deze op uit de database via view veiligheidsregio_huidig. Daar staat echter bij ons de juiste in (06).

**Comment by Oostjoost** [comment]
Zou inderdaad zo moeten zijn.... ik kijk even na waarom hij deze niet aanpast.

**Comment by Oostjoost** [comment]
Voorstel om dit op te lossen:
Kaartlaag weer opnemen vanuit de database ipv de dimensie_tables.

**Comment by ghost** [comment]
Als dat ervoor zorgt dat de juiste regio bij iedereen getoond wordt, helemaal goed.
