### ISSUE TITLE
[Feedback v3.3.9_beta3] Terrein aanmaken niet mogelijk

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#232]
QGIS melding:
```
CRITICAL
Laag Objecten BGT : PostGIS fout bij het toevoegen van objecten: ERROR: cannot insert into view "object_bgt"

DETAIL: Views that do not select from a single table or view are not automatically updatable.
HINT: To enable inserting into the view, provide an INSTEAD OF INSERT trigger or an unconditional ON INSERT DO INSTEAD rule.
```

Database log:
```
LOG:  statement: BEGIN
ERROR:  cannot insert into view "object_bgt"
DETAIL:  Views that do not select from a single table or view are not automatically updatable.
HINT:  To enable inserting into the view, provide an INSTEAD OF INSERT trigger or an unconditional ON INSERT DO INSTEAD rule.
2022-02-16 08:50:56.487 CET [4388] STATEMENT:  INSERT INTO "objecten"."object_bgt"("geom","id","datum_aangemaakt","datum_gewijzigd","basisreg_identifier","formelenaam","bijzonderheden","pers_max","pers_nietz_max","datum_geldig_tot","datum_geldig_vanaf","bron","bron_tabel","fotografie_id","bodemgesteldheid_type_id","typeobject") VALUES (st_geomfromwkb($1::bytea,28992),$2,NULL,NULL,'wordt gekoppeld in de database','test 3.3.9',NULL,NULL,NULL,NULL,NULL,'BGT','wordt gekoppeld in de database',NULL,NULL,NULL) RETURNING "id"
LOG:  statement: ROLLBACK
LOG:  statement: DEALLOCATE addfeatures
ERROR:  prepared statement "addfeatures" does not exist
STATEMENT:  DEALLOCATE addfeatures
LOG:  statement: ROLLBACK
WARNING:  there is no transaction in progress
```

Naar aanleiding van de feedback van issue https://github.com/OIV-NL-QGIS/QGIS_project/issues/224 heb ik alle rechten op oiv_admin gezet middels de voorgestelde queries. Daar is nu alles oiv_admin. 

Betreft versie: https://github.com/OIV-NL-QGIS/QGIS_project/releases/tag/v3.3.9_beta3

**Comment by Oostjoost** [comment]
![image](https://user-images.githubusercontent.com/23038880/154249789-ec183e45-036a-489e-b308-812b589d584f.png)

Wil je nakijken of deze rule er wel op staat in de DB? Ik vermoed dat die niet aanwezig is.

**Comment by Oostjoost** [comment]
Wil je daarnaast ook even kijken of bij de tabellen/view etc waar je oiv_admin eigenaar hebt gemaakt, recursief de rechten zijn gezet voor oiv_write (insert, update en delete) en oiv_read(select)?

Door iets aan te maken met de gebruiker oiv_admin in een script worden namelijk recursief direct ook de rechten gezet voor oiv_write en oiv_read. Ik vraag mij af of dit is gebeurd indien je alleen de owner hebt aangepast.

**Comment by ghost** [comment]
> ![image](https://user-images.githubusercontent.com/23038880/154249789-ec183e45-036a-489e-b308-812b589d584f.png)
> Wil je nakijken of deze rule er wel op staat in de DB? Ik vermoed dat die niet aanwezig is.

```
select r.rulename,
       c.relname as rule_table,
       case r.ev_type
         when '1' then 'SELECT'
         when '2' then 'UPDATE'
         when '3' then 'INSERT'
         when '4' then 'DELETE'
       end as rule_event
from pg_catalog.pg_rewrite r
  join pg_catalog.pg_class c on r.ev_class = c.oid
where c.relnamespace = 'objecten'::regnamespace
  and r.rulename <> '_RETURN';
```

```
object_upd,object_objecten,UPDATE
object_ins,object_objecten,INSERT
object_del,object_objecten,DELETE
object_terrein_ins,object_terrein,INSERT
object_terrein_upd,object_terrein,UPDATE
object_terrein_del,object_terrein,DELETE
object_grid_upd,object_grid,UPDATE
object_grid_ins,object_grid,INSERT
object_grid_del,object_grid,DELETE

```

**Comment by ghost** [comment]
> Wil je daarnaast ook even kijken of bij de tabellen/view etc waar je oiv_admin eigenaar hebt gemaakt, recursief de rechten zijn gezet voor oiv_write (insert, update en delete) en oiv_read(select)?
> 
> Door iets aan te maken met de gebruiker oiv_admin in een script worden namelijk recursief direct ook de rechten gezet voor oiv_write en oiv_read. Ik vraag mij af of dit is gebeurd indien je alleen de owner hebt aangepast.

Ik heb een `GRANT SELECT ON <schema>.<table/view> TO oiv_read;` gedaan voor alle tabellen en views binnen alle schemas. En een  `GRANT INSERT,UPDATE,DELETE ON <schema>.<table/view> TO oiv_write;` uitgevoerd. 
Daarmee zou alles goed moeten staan. Ook dat lost het helaas niet op.

**Comment by Oostjoost** [comment]
> select r.rulename,
>        c.relname as rule_table,
>        case r.ev_type
>          when '1' then 'SELECT'
>          when '2' then 'UPDATE'
>          when '3' then 'INSERT'
>          when '4' then 'DELETE'
>        end as rule_event
> from pg_catalog.pg_rewrite r
>   join pg_catalog.pg_class c on r.ev_class = c.oid
> where c.relnamespace = 'objecten'::regnamespace
>   and r.rulename <> '_RETURN';

Hij staat er dus niet tussen

**Comment by Oostjoost** [comment]
`CREATE RULE object_bgt_ins AS
    ON INSERT TO objecten.object_bgt DO INSTEAD  INSERT INTO objecten.object (geom, basisreg_identifier, formelenaam, bron, bron_tabel)  SELECT new.geom,
            b.identificatie,
            new.formelenaam,
            b.bron,
            b.bron_tbl
           FROM algemeen.bgt_extent b
          WHERE st_intersects(new.geom, st_curvetoline(b.geovlak))
         LIMIT 1
  RETURNING object.id,
    object.geom,
    object.datum_aangemaakt,
    object.datum_gewijzigd,
    object.basisreg_identifier,
    object.formelenaam,
    object.bijzonderheden,
    object.pers_max,
    object.pers_nietz_max,
    object.datum_geldig_tot,
    object.datum_geldig_vanaf,
    object.bron,
    object.bron_tabel,
    object.fotografie_id,
    object.bodemgesteldheid_type_id,
    ( SELECT o.typeobject
           FROM objecten.historie o
          WHERE (o.object_id = object.id)
         LIMIT 1) AS typeobject;`

**Comment by ghost** [comment]
Rule ontbrak inderdaad.
