### ISSUE TITLE
Geen datum tijd stempel bij bouwlaag bewerken

### ISSUE THREAD

**Issue by Joachim-Tempelaars** [OIV-NL-QGIS/OIV_project#233]
Bij het invullen van bouwlaag gegevens wordt de ingevulde gegevens wel opgeslagen maar krijgt geen datum tijd stempel mee

**Comment by Oostjoost** [comment]
Graag wat toelichting, want als ik bij een bouwlaag bijvoorbeeld een bouwdeel in geef wordt er een datum_gewijzigd geregistreerd.

**Comment by Oostjoost** [comment]
hetzelfde geldt voor een aanpassing van de geometrie

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/QGIS_project/commit/02b3307b95c8e9a77b11170abf507874f4ab53f4
