### ISSUE TITLE
[Feedback v3.3.9_beta3] Iconen geven vraagteken

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#237]
De blauwe sleutelkluis_hbr in het tabblad industrie geeft een vraagteken
Bluswater defect in het tabblad bluswater geeft een vraagteken

Betreft versie: https://github.com/OIV-NL-QGIS/QGIS_project/releases/tag/v3.3.9_beta3

**Comment by Oostjoost** [comment]
![image](https://user-images.githubusercontent.com/23038880/154532597-5bc6a92b-908c-4cc7-9493-41b651590551.png)

hoe kan ik dit reproduceren en welke versie betreft het?

**Comment by Oostjoost** [comment]
In script 3.3.0-3.3.1 ->
INSERT INTO bluswater.alternatieve_type (id, naam, symbol_name, size)
    VALUES (9999, 'Voorziening defect', 'bluswater_defect', 6) ON CONFLICT DO NOTHING;

INSERT INTO objecten.sleutelkluis_type (id, naam, symbol_name, size)
    VALUES (10, 'Sleutelkuis Havenbedrijf', 'sleutelkluis_hbr', 4) ON CONFLICT DO NOTHING;

En hier staat het gelijknamige symbool:
https://github.com/OIV-NL-QGIS/QGIS_project/blob/master/qgis_project/objecten/svg/bluswater_defect.svg
https://github.com/OIV-NL-QGIS/QGIS_project/blob/master/qgis_project/objecten/svg/sleutelkluis_hbr.svg

Kun je eens kijken of in bovenstaande tabellen ook deze waarden staan met bijbehorende "symbol_name"?

**Comment by Joachim-Tempelaars** [comment]
In de dimensie tabel sleutelkluis_type is de symbol_name "sleutelkluis_havenbedrijf".
Heb een copy gemaakt van de svg "sleutelkluis_hbr" en deze de bestandsnaam "sleutelkluis_havenbedrijf" gegeven.
Hierna wordt het symbol wel geplaatst en niet een ?.

Mogelijk dat dit het probleem is bij meerder symbols.
Voor de enkele symbols is het zo op te lossen. (wel melden om welke symbols het gaat)

Als de werkgroep styling klaar is met de IMROI styling pakken we de styling voor de OIV plug-in in zijn totaliteit op.

**Comment by Oostjoost** [comment]
Dank je wel Joachim.... dit is verhelderend voor het probleem. Deze 2 symbolen moeten een update krijgen in de database type tabel. Ik neem het op in het migratiescript van 3.3.9-3.4.0
