### ISSUE TITLE
[Feedback v3.3.9_beta3] Dieptelijnen WO

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#238]
In het tabblad waterongevallen werken de dieptelijnen niet, deze kun je alle 3 niet plaatsen

Betreft versie: https://github.com/OIV-NL-QGIS/QGIS_project/releases/tag/v3.3.9_beta3

**Comment by Oostjoost** [comment]
![image](https://user-images.githubusercontent.com/23038880/154534495-02be63f7-e795-4495-8705-f8b68d9c6e37.png)

Deze kan ik niet reproduceren.... misschien morgen even contact?

**Comment by Oostjoost** [comment]
kan ik er voor de laatste release voor 3.4.0 vanuit gaan dat deze invalid is?

**Comment by ghost** [comment]
Ik heb de volgende terugkoppeling gekregen: Lijkt of de dieptelijnen wel geplaatst worden maar niet zichtbaar zijn.. 


Ik heb het net zelf ook nog even geprobeerd, de lijn teken je en wordt netjes geinsert:
```
2022-02-23 09:47:56.323 CET [3592] LOG:  statement: BEGIN
2022-02-23 09:47:56.336 CET [3592] LOG:  execute addfeatures: INSERT INTO "objecten"."object_isolijnen"("geom","id","hoogte","omschrijving","object_id","formelenaam","applicatie","datum_geldig_vanaf","datum_geldig_tot","typeobject") VALUES (st_multi(st_geomfromwkb($1::bytea,28992)),$2,'-9',NULL,1995,NULL,'OIV',NULL,NULL,NULL) RETURNING "id"
2022-02-23 09:47:56.336 CET [3592] DETAIL:  parameters: $1 = '\x0105000000010000000102000000040000006e90df31aa510a4120f567759ccc1a41429fb1c9a94b0a4179881bb72ecc1a4187da1d86e0490a4149b3246bcec71a418629c6144f560a41bd4ac3f469c91a41', $2 = NULL
2022-02-23 09:47:56.351 CET [3592] LOG:  statement: DEALLOCATE addfeatures
2022-02-23 09:47:56.351 CET [3592] LOG:  statement: COMMIT
```

In de database:
![isolijnen](https://user-images.githubusercontent.com/73171956/155286985-56546f06-b077-4dd2-a1f0-a46499b26e4c.png)


Maar op de tekening zie ik de 9m lijn die ik tekende niet terug. In de view `view_isolijnen `staan 0 records. Gegenereerde DDL van die view:
```
create or replace view objecten.view_isolijnen
            (id, geom, datum_aangemaakt, datum_gewijzigd, hoogte, omschrijving, object_id, formelenaam) as
SELECT b.id,
       b.geom,
       b.datum_aangemaakt,
       b.datum_gewijzigd,
       b.hoogte,
       b.omschrijving,
       b.object_id,
       o.formelenaam
FROM objecten.object o
         JOIN objecten.isolijnen b ON o.id = b.object_id
         JOIN (SELECT h.object_id
               FROM objecten.historie h
                        JOIN (SELECT historie.object_id,
                                     max(historie.datum_aangemaakt) AS maxdatetime
                              FROM objecten.historie
                              WHERE historie.status::text = 'in gebruik'::text
                              GROUP BY historie.object_id) hist
                             ON h.object_id = hist.object_id AND h.datum_aangemaakt = hist.maxdatetime) part
              ON o.id = part.object_id
WHERE (o.datum_geldig_vanaf <= now() OR o.datum_geldig_vanaf IS NULL)
  AND (o.datum_geldig_tot > now() OR o.datum_geldig_tot IS NULL)
  AND o.datum_deleted IS NULL
  AND b.datum_deleted IS NULL;

alter table objecten.view_isolijnen
    owner to oiv_admin;

grant select on objecten.view_isolijnen to oiv_read;

grant delete, insert, update on objecten.view_isolijnen to oiv_write;

```

**Comment by Oostjoost** [comment]
Ik zie het probleem....

FROM objecten.object o
         JOIN objecten.isolijnen b ON o.id = b.object_id
         JOIN (SELECT h.object_id

moet zijn:
FROM objecten.object o
         JOIN objecten.isolijnen b ON o.id = b.object_id
         LEFT  JOIN (SELECT h.object_id

ik zal het opnemen in de laatste scripts

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.3.9-3.4.0-beta1.sql
