### ISSUE TITLE
[Feedback v3.4.0-beta1-Zaandam] Fout in migratiescript 

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#244]
Betreft script https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.3.9-3.4.0-beta1.sql

```
SET role oiv_admin;
SET search_path = objecten, pg_catalog, public;

UPDATE objecten.sleutelkuis_type SET naam = 'Sleutelkuis Havenbedrijf', symbol_name = 'sleutelkluis_havenbedrijf'
WHERE id = 10;

UPDATE bluswater.alternatieve_type SET naam = 'Voorziening defect', symbol_name = 'bluswater_defect'
WHERE id = 9999;
```

`objecten.sleutelkuis_type` moet worden: `objecten.sleutelkluis_type` (letter L vergeten)

`search_path = objecten, pg_catalog, public;` moet worden: `search_path = objecten, bluswater, pg_catalog, public;` (schema bluswater vergeten)

**Comment by ghost** [comment]
Heb het nu even handmatig aangepast zodat er direct getest kan worden met de nieuwe release.

**Comment by Oostjoost** [comment]
was reeds aangepast, jullie hebben net te vroeg het script gedownload denk ik.

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.3.9-3.4.0-beta1.sql
