### ISSUE TITLE
Installatie op systeem voor alle gebruikers functioneert niet

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#246]
Installatie van de nieuwe release (https://github.com/OIV-NL-QGIS/QGIS_project/releases/tag/v3.4.0_beta1) op een nieuwe QGIS 3.16 LTR installatie op onze test-VM.

Installatie met mijn eigen user-account uitgevoerd met admin-rechten.

Voor alle gebruikers op de test machine staat in deze map géén OIV plugin (bij mij dus ook niet):
`C:\Users\--username--\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins`

Hier staat wel de OIV plugin map:
`C:\Program Files\QGIS 3.16\apps\qgis-ltr\python\plugins`
`C:\ProgramData\OIV-3.4.0`

Daarmee lijkt het dus - zoals besproken en ook de bedoeling is - dat je de plugin system-wide kan installeren ipv per gebruiker. Bij mij werkt de installatie en het gebruik van de plugin (inhoudelijke functionele testen daargelaten, daar gaan de collega's over met het testproces). Tijdens de installatie kwamen er geen foutmeldingen naar voren. Ook de QGIS caches zijn voor alle gebruikers verwijderd.

Feedback van onze collega die aan het testen is:
![ii1](https://user-images.githubusercontent.com/73171956/155953286-db65f199-2d52-41d4-91c0-5ba14a2ec400.png)
![ii2](https://user-images.githubusercontent.com/73171956/155953311-2eede7c5-ea51-484a-95bf-9a528b99bf27.png)

De plugin lijkt echter wel geinstalleerd te zijn:
![ii3](https://user-images.githubusercontent.com/73171956/155953332-4a9ecab6-7484-43c8-b3eb-684025b73a24.png)

**Comment by Oostjoost** [comment]
Plugin heeft niets te maken met de pg_service file voor de connectie met de database. Dit lijkt op foutieve inloggegevens welke zijn opgegeven tijdens de installatie.

Zou je bij deze collega eens kunnen kijken naar pg_service.conf file in c:/programdata/oiv.....

**Comment by Oostjoost** [comment]
let wel.... voor de allernieuwste 3.16 versie (volgens mij 3.16.15) is ook een msi installer gebruikt, waarbij niet in het register is weggeschreven wat de installpath van QGIS is.

**Comment by ghost** [comment]
Het pg_service bestand is correct geinstalleerd, deze heb ik vanmorgen zelf geplaatst in: `C:\ProgramData\OIV-3.4.0\pg_service.conf`

**Comment by Oostjoost** [comment]
kan je eens kijken bij de omgevingsvariabele PGSERVICEFILE, of die wel bestaat?
![image](https://user-images.githubusercontent.com/23038880/156007540-5d9f679d-5073-4332-903c-3cc9c16bcff3.png)

**Comment by ghost** [comment]
Yes, die bestaat ook:
![ii5](https://user-images.githubusercontent.com/73171956/156008259-3f418c63-8678-4b4f-830f-d5837a027f2c.png)

**Comment by ghost** [comment]
Zojuist ook de rechten van het bestand voor de zekerheid gecheckt, maar zowel admins als reguliere gebruikers hebben lees- en schrijftoegang tot het bestand. Dat is het dus ook niet.

**Comment by Oostjoost** [comment]
Er staat ook niet per ongeluk 2x een [oiv] configuratie in de pg_service file? Daar had ik laatst last van...

**Comment by ghost** [comment]
Nee, ook dat is niet het geval.

**Comment by Oostjoost** [comment]
iets anders kan het eigenlijk niet zijn, voor de service verbinding met de database zijn drie dingen noodzakelijk:

- Omgevingsvariabele welke verwijst naar de locatie van de pg_service.conf
- Juiste credentials in de pg_service file
- rechten hebben om een connectie op te zetten naar de database
Staat verder volledig los van gehele OIV.

Je zou het volgende eens kunnen proberen om OIV uit te sluiten:
1. Qgis openen zonder OIV
2. Een PostGIS connectie maken via een service
3.
![image](https://user-images.githubusercontent.com/23038880/156013265-c3862c9b-a9fc-4439-8a8b-2ad805e765f4.png)

Als je dan ook niet bij de database kunt komen zit er iets fout in de bovenstaande 3 punten. Database parameter mag leeg blijven.

**Comment by ghost** [comment]
Na een reboot leek het probleem verholpen. Probleem is nu weg, gebruiker heeft niets aangepast daarna en ik ook niet.

**Comment by ghost** [comment]
Issue heropend. Bij de installatie van 3.4.0 moest ik bij gebruikers de OIV plugin map in hun gebruikersmap plaatsen i.p.v. de systeem-installer zoals we voorheen hadden. Ik dacht dat bij 3.16 dit nog zo zou blijven, en bij 3.22 de gebruikersmap wel een rol zou spelen.

**Comment by Oostjoost** [comment]
de laatste versie van QGIS 3.16(.15) is tevens een MSI installer geworden. Ook hier is het dus niet mogelijk om het installatie pad te achterhalen via het register. Dit was bij 3.16.14 nog wel mogelijk. De installer wil nog wel de installatie doen in de ltr map, maar ls het register entry niet bestaat kan hij niet installeren.

Elke MSI installer registreet in Windows een register key welke overeenkomt met de installatie. Dit is een UUID welke naar mijn inzicht altijd anders is. Hierdoor weet de uninstaller van Windows wel waar QGIS is geïnstalleerd maar dit kan ik niet in het register achterhalen.

Lastig....

**Comment by ghost** [comment]
En wat nu als we een standaard gevuld veld hebben bij de installer van het project? 
Je moet dit immers toch doorlopen bij de installatie. Kan je daar niet een textveld toevoegen waarin het standaard QGIS pad staat, maar dit overschrijfbaar is met een aangepast installatiepad naar de QGIS applicatie directory? Dan is de noodzaak tot het ophalen van die info uit het register ook verdwenen en is dat geen issue meer.

**Comment by Oostjoost** [comment]
Dat is zeker een oplossing... had ik ook al aan gedacht. Ik vraag me alleen af of iedereen dan snapt wat daar moet worden ingevuld. Voor nu wil ik voorstellen om het dan maar zo op te lossen.

**Comment by ghost** [comment]
Gisteren heb ik dit in de werkgroep besproken, en iedereen was akkoord met die optie

**Comment by ghost** [comment]
Even heropend na een reactie op mijn topic: https://gis.stackexchange.com/questions/424892/get-installation-path-for-qgis-3-16-and-3-22
Is dat (in de toekomst) mogelijk een interessante workaround?
Voor nu is de huidige optie prima.

**Comment by Oostjoost** [comment]
deze workaround met de product-key had ik ook gevonden echter is dit via het huidige NSIS scripts niet op te halen. Mogelijk kunnen we in de toekomst kijken of we er een ander soort microsoft installer van kunnen maken

**Comment by Oostjoost** [comment]
Aangezien de relatie met #271 lijkt het mij verstandig om deze beide issues te sluiten en eventueel een nieuw issue aan te maken ten behoeve van het maken van een nieuwe installer.
