### ISSUE TITLE
Verwijderen bouwlaag

### ISSUE THREAD

**Issue by 31081970** [OIV-NL-QGIS/OIV_project#247]
Bouwlagen op diverse manieren toegevoegd. Overnemen van BAG, zelf tekenen en overnemen van andere bouwlaag, deze bouwlagen zijn vervolgens niet meer te verwijderen. Q-gis laat alle stappen zien als normaal maar de bouwlaag blijft zichtbaar, geeft ook geen foutmelding.

**Comment by ghost** [comment]
Om welke versie van QGIS, de plugin en de database gaat het?

**Comment by Oostjoost** [comment]
Dit is correct.... alle lagen reageren op de juiste wijze op de soft-delete. Echter de bouwlagen laag zelf niet. Deze moet nog gefilterd worden op datum_deleted IS NULL. Nu worden verwijderde bouwlagen ook nog getoond.

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.4.0-beta1-3.4.0.sql
resolves #247

**Comment by ghost** [comment]
Probleem speelt nog steeds. Bovenstaand migratiescript gedraaid (overigens nieuw issue bij `bouwlagen_ins `, zie https://github.com/OIV-NL-QGIS/QGIS_project/issues/249), maar dan blijft het issue. Staat - denk ik -los van de insert rule?
![a1](https://user-images.githubusercontent.com/73171956/156158797-1e264b23-d596-463f-99d9-a165ec5c5f40.png)
![a2](https://user-images.githubusercontent.com/73171956/156158803-21966d0d-3ae7-4485-8996-d5dee7d5a09e.png)
![a3](https://user-images.githubusercontent.com/73171956/156158807-faa57677-2614-47d0-a76f-145d82337eb5.png)
![a4](https://user-images.githubusercontent.com/73171956/156158812-bceb94fc-8776-41c1-b96b-4d9b5f761ed6.png)

**Comment by Oostjoost** [comment]
Is niet alleen een nieuw script, maar ook een aanpassing in het QGIS project voor nodig. Die was al gedaan, maar die is natuurlijk nog niet gereleased. Het comment was een beetje misleidend, niet alleen het script los dit dus op.
