### ISSUE TITLE
Actieve bouwlaag blijft achter bij tekenen op nieuwe bouwlaag

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#248]
Tijdens het aanmaken en vervolgens tekenen op bouwlaag X wordt dit niet getoond als actieve bouwlaag. 
In dit testvoorbeeld heb ik bouwlaag 1 aangemaakt, vervolgens een nieuwe bouwlaag toegevoegd (2) en dan blijft bovenin de taakbalk staan: Actieve bouwlaag 1

**Comment by ghost** [comment]
Ter verduidelijking, het gaat om deze dropdown:
![ii4](https://user-images.githubusercontent.com/73171956/155992101-42712a11-c4c1-4181-b31b-54d5752a0acc.png)

**Comment by Oostjoost** [comment]
Dit is altijd al zo geweest.....
De bouwlaag switch in de werkbalk is alleen voor het switchen van bouwlagen zonder gebruik van de plugin. Deze wordt gedeactiveerd zodra de plugin wordt gestart en hier wordt niet meer mee gedaan. In de plugin zelf wordt te allen tijde het juiste bouwlaag nummer weergegeven.

Indien de bouwlaag boven in wel moet meelopen dan dit graag als wens opnemen voor een volgende versie.

**Comment by ghost** [comment]
We laten deze maar even op de backlog staan. Geen prio, bovendien hebben we daar nu geen beschikbare uren voor.
