### ISSUE TITLE
[Feedback v3.4.0-beta1-Zaandam] Migratiescript issue

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#249]
Nieuwe versies gedraaid met de juiste rechten:
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.3.9-3.4.0-beta1.sql
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.4.0-beta1-3.4.0.sql

```
CREATE RULE bouwlagen_ins AS
ON INSERT TO objecten.bouwlaag_bouwlagen 
DO INSTEAD  
INSERT INTO objecten.bouwlagen (geom, bouwlaag, bouwdeel, pand_id)
VALUES (new.geom, new.bouwlaag, new.bouwdeel, new.pand_id)
RETURNING bouwlagen.id,
bouwlagen.geom,
bouwlagen.datum_aangemaakt,
bouwlagen.datum_gewijzigd,
bouwlagen.bouwlaag,
bouwlagen.bouwdeel,
bouwlagen.pand_id,
bouwlagen.datum_deleted
```

**ERROR: RETURNING list's entry 7 has different type from column "fotografie_id"
Detail: RETURNING list entry has type character varying, but column has type integer.**

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.4.0-beta1-3.4.0.sql
is opgelost... zat een discrepantie op fotografie_id binnen de verschillende gebruikers. Wordt nu gekeken of hij bestaat en waar nodig wordt hij aangemaakt. Daarna pas wordt de view aangemaakt en werkt het als het goed is.
