### ISSUE TITLE
[Feedback v3.4.0-beta1-Zaandam] Getekende lijnen en symbolen nabijgelegen objecten pas zichtbaar na klik op OIV tool

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#250]
In een aantal gevallen worden lijnen en symbolen van rondomliggende objecten niet getoond. Van een deel ook weer wel, zoals in dit voorbeeld op de testomgeving:
![x1](https://user-images.githubusercontent.com/73171956/156156235-507c46cc-5818-4e5a-9418-2f0ef0a856e8.png)

Na een klik op de OIV tool verschijnen deze wel. Terwijl hertekenen aan staat, en daarvoor ook zoom- en pan-acties niet helpen op de lagen te renderen. Na de klik verschijnen deze wel:
![x2](https://user-images.githubusercontent.com/73171956/156156242-fd214e8a-12a5-41ad-801d-bcc9f999bb65.png)

**Comment by Oostjoost** [comment]
Is dit op de één of andere wijze te reproduceren, zodat ik kan onderzoeken waardoor dit zou komen? Komt dit ook bij anderen voor?

**Comment by Oostjoost** [comment]
Als ik "zoek de verschillen" doe op bovenstaande afbeeldingen:
Lijkt het of de eerste afbeelding is gefilterd op bijvoorbeeld bouwlaag 2 via de "actieve bouwlaag" en na het openen van de plugin, wordt automatisch geschakeld naar bouwlaag 1, waardoor er geheel andere zaken zichtbaar worden.

Dit is bijna zeker de veroorzaker van dit "issue".
