### ISSUE TITLE
DXF import werkt niet als er meerdere bouwlagen zijn.

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/OIV_project#255]
DXF import werkt niet als er meerdere bouwlagen zijn.

oorzaak de aanmaker heeft meerdere dezelfde bouwlagen op elkaar liggen als je dan op de bouwlaag moet klikken kan QGIS niet uit de juiste bouwlaag kiezen.

**Comment by Oostjoost** [comment]
nog niet helemaal verholpen......
