### ISSUE TITLE
Verwijderen van o.a. bouwlaag en object geeft problemen

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#261]
We zijn nog aan het testen met het verwijderen van bouwlagen en het volgende komt naar boven:
- Als je bijvoorbeeld bouwlaag 2 verwijderd dan gaat dit goed en is de bouwlaag incl. gekoppelde symboliek verwijderd
- Als je bouwlaag 1 verwijderd dan is de bouwlaag weg maar de symboliek blijft staan
- Als je het hele object verwijderd dan verdwijnt het terrein met het blauwe i’tje maar blijft de symboliek staan

Betreft de laatste 3.4.0 release op QGIS 3.16

**Comment by Oostjoost** [comment]
3.4.0 is gereleased, als er nu nog zaken zijn is destijds afgesproken om hier voor 3.4.1 en 3.4.2 te reserveren als patch releases.

Dit is inderdaad te reproduceren en komt door het soft-deleting. De bouwlaag wordt niet weggegooid en dus ook niet de pictogrammen/symbolen. De database relaties werken alleen cascade als er een delete wordt doorgevoerd. Dit wordt nu niet gedaan en dus worden ook niet de gerelateerd objecten verwijderd.

Bij het verwijderen van een object geldt hetzelfde.

Wat overigens niet de bedoeling is en niet zo werkte, is dat het verwijderen van een i-tje ook de bouwlagen en de daar aan gerelateerde objecten worden verwijderd. Er is geen database relatie tussen object en bouwlaag.

**Comment by Oostjoost** [comment]
Via onderstaande functie welke bij een soft-delete van een bouwlaag gaat worden aangeroepen wordt in alle gerelateerde tabellen de gerelateerd objecten ook ge-soft-deleted.

Dezelfde functie wordt opgezet voor objecten.
CREATE OR REPLACE FUNCTION objecten.func_soft_delete_cascade_bouwlaag()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
    DECLARE
       fk_table TEXT;
       fk_schema TEXT;
    BEGIN
		FOR fk_table, fk_schema IN
			SELECT 
			       fk_tco.table_schema as fk_table,
			       fk_tco.table_name AS fk_schema
			FROM information_schema.referential_constraints rco
			JOIN information_schema.table_constraints fk_tco ON rco.constraint_name = fk_tco.constraint_name AND rco.constraint_schema = fk_tco.table_schema
			JOIN information_schema.table_constraints pk_tco ON rco.unique_constraint_name = pk_tco.constraint_name AND rco.unique_constraint_schema = pk_tco.table_schema
			WHERE pk_tco.table_name = 'bouwlagen' AND pk_tco.table_schema = 'objecten'
		LOOP
			RAISE NOTICE 'i want to update % and % with id %', fk_table, fk_schema, OLD.id;
			EXECUTE format('UPDATE %I.%I SET datum_deleted = now() WHERE bouwlaag_id = $1;', fk_table, fk_schema)
			USING OLD.id;
		END LOOP;
        RETURN OLD;
    END;
    $function$
;

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.4.0-3.4.1.sql
