### ISSUE TITLE
Schakelen van prod naar test in dezelfde plug-in

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/OIV_project#262]
We willen graag vanuit dezelfde plugin kunnen 'schakelen' van de ene naar de andere omgeving (prod en test)

Een aandachtspunt is dat de verschillende omgevingen niet perse op dezelfde server moeten staan. (Carlo voor de uitleg)

**Comment by ghost** [comment]
Zoals net besproken in de werkgroep, is het niet gewenst om binnen dezelfde database configuratie te switchen van de prod naar test-database. Omdat je daarmee bv. PostgreSQL updates niet kan scheiden tussen de databases. 
Gewenst is om onderstaande te bereiken:
- Switchen tussen prod- en test-database op dezelfde server, met dezelfde credentials
- Switchen tussen een prod- en test-database met een eigen config-bestand, zodat je én andere credentials kan gebruiken, én een andere server kan invullen voor de testomgeving, dat hoeft dan niet gelijk te zijn aan je productie-omgeving (in ons geval).

**Comment by Oostjoost** [comment]
het worden ook 2 connectie files gebruikt waartussen geswitched wordt, dus geen probleem als het meerdere servers zijn

**Comment by Oostjoost** [comment]
belangrijk om te vermelden is dat beide backends (databases) qua versie met de plugin moeten kunnen samenwerken

**Comment by ghost** [comment]
Dat is prima, top. Dat is ook zoals we het voor ogen hadden. 
Ging mij erom dat je bv. postgres kan updaten van 12 naar 13 (om maar iets te noemen), zonder de inhoudelijke objecten database bij te werken. Dan draai je qua OIV tooling dus hetzelfde, maar kun je de achterliggende versies van oa postgis en postgres bijwerken en dit eerst testen. Dat beide databases dan dezelfde versie van de OIV tooling draaien is vanzelfsprekend.

**Comment by Oostjoost** [comment]
![image](https://user-images.githubusercontent.com/23038880/161224435-89e54c7f-2d2b-455a-8038-579106479b47.png)
![image](https://user-images.githubusercontent.com/23038880/161224680-6e06237a-9211-48f1-abea-babfbe9ce869.png)

https://user-images.githubusercontent.com/23038880/161224789-cb8ece27-8afa-436a-8172-1beb8781e7a7.mp4

**Comment by Oostjoost** [comment]
Na het switchen in de oiv plugin settings wordt de pg_service.conf vervangen door hetzij de test of de prod versie. Hierdoor wordt altijd de pg_service.conf gebruikt.
