### ISSUE TITLE
Opstarten snelkoppeling OIV project geblokkeerd door Windows-beveiliging 

### ISSUE THREAD

**Issue by rbouwer-gis** [OIV-NL-QGIS/OIV_project#263]
Wanneer de snelkoppelingen van OIV met QGIS versie 3.22 op het bureaublad worden geopend geeft Windows een beveiligingsmelding dat de "Actie is geblokkeerd". Vanwege user rechten kunnen deze problemen ontstaan.
Bij het opstarten worden een aantal .bat files in de startup (doel) gebruikt die niet noodzakelijk zijn voor het opstarten van het OIV project met QGIS 3.22.

 - Besturingssysteem en versie: Windows 10 Enterprise
 - Intune installatie QGIS en OIV
 - QGis versie: 3.22

Zie onderstaande oplossing, graag in nieuwe installer verwerken.
Deze werkt niet met QGIS 3.22 ---- C:\ProgramData\OIV-3.4.0\nircmd.exe exec hide "C:\PROGRA~1\QGIS32~1.5\bin\qgis-ltr..bat" "C:\ProgramData\OIV-3.4.0\OIV_Objecten.qgs" --customizationfile "C:\ProgramData\OIV-3.4.0\ini\oiv.ini"

Oplossing:
"C:\Program Files\QGIS 3.22.5\bin\qgis-ltr-bin.exe" "C:\ProgramData\OIV-3.4.0\OIV_Objecten.qgs"

![Beveiligings melding Windows](https://user-images.githubusercontent.com/60362584/160395339-ecee21cb-001a-4cf7-bbb3-2de5f60963c4.PNG)

**Comment by Oostjoost** [comment]
Samen met VRNHN deze oplossing gemaakt.... kleine aanpassing aan de installer door nircmd eruit te halen. De ini file wordt ook nergens gebruikt.
