### ISSUE TITLE
Installatie-pad in setup wordt niet gebruikt

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#271]
In de nieuwe 3.4.1 release voor QGIS 3.16 is een invoerveld beschikbaar waar de plugin geinstalleerd moet worden. Dat is hoe wij het voor ogen hadden, top.
![setup1](https://user-images.githubusercontent.com/73171956/168066512-dbed10cf-5620-4965-ae17-e0aeb143ed30.png)

Probleem is alleen dat de ingevoerde waarde niet wordt gebruikt voor de installatie zelf. Dat komt toch nog in de gebruikersmap terecht:
![setup2](https://user-images.githubusercontent.com/73171956/168066501-e2e01049-df0f-4006-835d-5519b6458110.png)

**Comment by Oostjoost** [comment]
Net getest in de 3.22 installer en daar gaat het wel goed. Ik zal even vergelijken met de 3.16 installer waarom dit niet goed gaat

**Comment by Oostjoost** [comment]
Na de vergelijking van de installlers blijkt dat er geen enkel verschil is. Ook na het testen op mijn eigen systeem met het zelf aangeven van een installatie-pad kiest hij de juiste locatie om de installatie te doen. Zouden jullie dit nogmaals in de testfase goed willen testen.
Mogelijk heeft het te maken met wel/niet schrijfrechten op de locatie waar je de plugin wilt wegschrijven. Dan moeten we misschien daar wat aan doen.
ik sluit nu dit issue om 3.4.2 af te kunnen maken. Mocht het niet goed zijn dan heropenen we het issue.

**Comment by ghost** [comment]
Heropend, dit speelt nog steeds in release https://github.com/OIV-NL-QGIS/QGIS_project/releases/tag/v3.4.2_beta1.
Run deze als admin, dus schrijfrechten voldoende.

**Comment by ghost** [comment]
![plugin1](https://user-images.githubusercontent.com/73171956/187419119-943f01bc-87cb-40df-baf7-10b10e4451c1.png)
![plugin2](https://user-images.githubusercontent.com/73171956/187419124-f67bf25a-b76c-4711-8a5a-583593cf49ee.png)

**Comment by Oostjoost** [comment]
Bij mij wordt hij in beide versies wel in de juiste folder geïnstalleerd, maar klopt alleen het pad in de "samenvatting" van de installatie niet. Zoals in de screenshot te zien is. Dit zal ik aanpassen.

**Comment by Oostjoost** [comment]
De samenvatting klopt weldegelijk en zet hem ook op de juiste locatie neer. Ik kan dit echt niet reproduceren.
![image](https://user-images.githubusercontent.com/23038880/188976350-09891e7c-7a99-42da-9731-7f753403f8d4.png)
![image](https://user-images.githubusercontent.com/23038880/188976854-5bb20e74-1304-4470-b054-b67b484e1584.png)

**Comment by Oostjoost** [comment]
Misschien een keer via Teams meekijken? Zijn er anderen bij wie dit ook voorkomt?

**Comment by ghost** [comment]
Ik wilde een screencast voor je maken maar daarin staan alleen de bovenstaande 2 screens, dus dat voegt weinig toe denk ik. 
We runnen de installer als admin, voeren het systeem-pad in ipv de gebruikers-appdata folder, maar de map komt alsnog in de gebruikers-appdata folder terecht.

**Comment by Oostjoost** [comment]
![image](https://user-images.githubusercontent.com/23038880/192996368-7dad410d-df2e-4f7a-924d-00f16a4863e1.png)

Ik denk dat het dan toch een rechten kwestie is want ook in de program files map kan ik zonder moeite een installatie doen. Ook bij de samenvatting "laatste pagina" van de installer toont hij netjes het juiste pad.

**Comment by Oostjoost** [comment]
workaround is de oiv.zip (plugin) zelf op de juiste locatie uit te pakken.

Wat mij wel is opgevallen dat hij indien er een bestaande plugin staat, deze niet overschrijft. Mogelijk zorgt dat voor het idee dat er geen nieuwe versie wordt neergezet. Zouden jullie de map oiv in de pad uit bovenstaande screenshot eens handmatig willen verwijderen en dan de installatie nogmaals proberen?

**Comment by Oostjoost** [comment]
Ik heb de installer zo aangepast dat hij eerst een bestaande map "oiv" verwijderd en dan de nieuwe plugin plaatst. Als dit het probleem was dan zou het nu opgelost moeten zijn met de volgende installer.

**Comment by Oostjoost** [comment]
Na nog even testen, blijkt het dus inderdaad fout te gaan indien er een pad wordt geknipt en geplakt bij de locatie keuze van de plugin. Het gaat wel goed indien je via het keuze knopje bladert naar de juiste locatie.
Wat mij betreft is deze dan ook afgesloten en afgehandeld.
