### ISSUE TITLE
Recreatiegebied toevoegen

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#276]
Graag het Type Object "Recreatiegebied" toevoegen.

**Comment by Joachim-Tempelaars** [comment]
Onder func terrein punten lijnen en vlakken toevoegen om dit in te vullen

**Comment by Oostjoost** [comment]
![image](https://user-images.githubusercontent.com/23038880/184248710-e355b377-3cc7-41ef-9439-641c6a8551ec.png)
