### ISSUE TITLE
Markering voor tekenen in Bouwlaag of Terrein

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#278]
Je kunt niet (blijvend) zien welke functie je geselecteerd hebt: Terrein of Bouwlaag. 
Misschien is dit aan te geven door er een ‘Keuzerondje’ voor te plaatsen.

**Comment by Oostjoost** [comment]
![image](https://user-images.githubusercontent.com/23038880/184244064-db2e44e1-fd6a-459f-933b-1fe813bc2067.png)
