### ISSUE TITLE
Meerdere pictogrammen tegelijk verwijderen

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#279]
Per keer is via de plugin maar 1 object/pictogram te verwijderen.
Kan door het aanklikken van het prullenbakje meerdere objecten/pictogrammen tegelijk verwijderd worden.

**Comment by Oostjoost** [comment]
IS teveel werk om nu even aan te passen voor versie 3.4.2
Is een nieuwe feature en niet het oplossen van een probleem

**Comment by Oostjoost** [comment]
Inschatting om dit te ontwikkelen is 8u. Er moet best wat aangepast worden om een multiselect aan te maken. Het kan meevallen, maar dit is mijn eerste inschatting

**Comment by IrenevanderZwan** [comment]
Ik heb er een VRK label aangehangen, ervan uitgaande dat we hier niet alleen over pictogrammen praten maar over alle tekenobjecten, dus ook lijnen en labels.

**Comment by CarloNannings** [comment]
Ten aanzien van GitHub issue #279 de volgende aanvulling:

Soms moet een Bouwlaag of Repressief object gedeeltelijk of in zijn geheel verwijderd worden. Bijv. door sloop, brand, einde evenement of correctie van het bag contour.
Het zou mooi zijn als de betreffende elementen geselecteerd kunnen worden met een polygoon en daarna collectief verwijderd kunnen worden.
Deze functie toevoegen aan submenu [Verwijderen] van zowel Terrein als Bouwlaag.

![image](https://github.com/user-attachments/assets/ff8d40a0-5c2f-4812-9c03-cad84cbc9990)

Voor de functie van knop Bouwlaag > Verwijderen betekent dit een uitbreiding van deze functie omdat deze knop nu de mogelijkheid geeft om direct een hele bouwlaag te verwijderen. 

Om ongewenst verwijderen van elementen te voorkomen de selectie beperken tot de elementen behorende bij het geselecteerde Terrein of Bouwlaag. Indien nodig kan door het aan- of uitzetten van lagen een selectie gemaakt worden van lijnen, vlakken, pictogrammen, etc. Alleen de resterende, zichtbare elementen dienen verwijderd te worden. De geselecteerde elementen roze laten oplichten en pas na bevestiging, zo mogelijk met opgave van het aantal elementen, de selectie verwijderen.

**Comment by Oostjoost** [comment]
Is het niet veel logischer om op het tekentabblad een polygoon selecttool te gebruiken waarmee je meerdere objecten kunt selecteren en dan op het prullenbakje kunt klikken om ze weg te gooien? Alles wat je tekent komt bij tekenen vandaan, en daar verwijder je nu ook één getekend object
