### ISSUE TITLE
Hulpteksten bij selecteren Terrein of Object

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#280]
Als je op één van de twee vlakken (“Terrein” of “Object”) klikt gebeurt er niets! 
Meestal geeft ergens op klikken een reactie zoals een vervolgactie, volgend scherm of iets dergelijks.
Dus wat te doen na klikken op een vlak? Zet dat (na klikken op de knop) tekstueel er onder, bijvoorbeeld :
•	Bij klikken op knop ‘Terrein of Gebied’: “Klik op (blauwe) Object dot” (niet: “Klik op ‘i-tje’ “ want dat wordt een figuurtje)
•	Bij klikken op knop met blauwe blokjes (Object): “Klik op (gele) Bouwlaag”

Deze hulptekst kan ook al als pop-up label getoond worden zodra je er met je muis boven hangt maar beter is aan te geven wat te doen nadat je er op geklikt hebt.

**Comment by Oostjoost** [comment]
![image](https://user-images.githubusercontent.com/23038880/184243952-4074e6c7-c7e3-4340-8819-cc5815efb7ed.png)
