### ISSUE TITLE
Probleem matrix-codes

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/OIV_project#283]
Er was bij de VRF een issue met de matrix-codes. Dit kwam door de dimensietabel. Het is bij de VRF opgelost. NHN heeft dezelfde issue. Het probleem was als het goed is opgelost in de volgende release. Even een check of dit ook zo is....

**Comment by Oostjoost** [comment]
Opgelost in 3.4.2, tabel direct vanuit de database ipv dimensie db
