### ISSUE TITLE
Filteren in OIV plugin

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#287]
‘Filter repressief object’ is wel te openen maar niet te sluiten. 

Waarom staat er permanent ‘Filter op datum’? Dat is een optie. 

Waarom staat er een checkbox voor de Keuzelijst: Evenement, Gebouw, Natuur, Waterongeval. Een selectie maken en een klik op de filterknop zou moeten volstaan. 
En waarom Waterongeval in plaats van Waterkaart of alleen Water of iets dergelijks. Er staat ook niet Gebouwbrand of Natuurgeweld! 

Aan de selectielijst bijvoorbeeld ‘i-tjes’ toevoegen (welke moeten nog omgezet worden?)

Vanaf: en Tot: alleen actief maken als gefilterd wordt op Evenement. De checkboxen kunnen dan vervallen; controleren op geldige datum(s). 

Via de Attributentabel kan er niet meer gefilterd worden op gemeente. Dit in combinatie met filteren op Status en Actualisatie is belangrijk voor het bepalen welk volgend object op te pakken.

**Comment by CarloNannings** [comment]
Misschien meenemen met het aanpassen van de OIV menu structuur in 3.5.0 als iedereen akkoord is.

**Comment by Oostjoost** [comment]
Er staat geen beschrijving hoe het dan wel moet worden, hier kan ik niks mee.
Graag eerst een duidelijke omschrijving en beschrijving hoer het moet werken. Voorstel om dit door te schuiven want betreft nieuwe functionaliteit in plaats bug-fixing. 

Voor nu haal ik hem uit deze milestone

**Comment by CarloNannings** [comment]
Komen we op terug. Mag nu vervallen
