### ISSUE TITLE
Symbolen in Alternatieve bluswater dubbel

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/OIV_project#289]
Hieronder zie je 2 geboorde putten staan welke ingetekend zijn op de alternatieve bluswater laag in Qgis.
De rechter (blauwe) is wel te zien in de alternatieve bluswater laag in LiveOp, maar de linker is niet te zien in de alternatieve bluswater laag in LiveOp.
Zouden jullie hier eens naar willen kijken en dan eventueel 1 van de symbolen willen verwijderen uit de keuzemogelijkheden zodat er geen verwarring ontstaat over welke we moeten selecteren?

![image](https://user-images.githubusercontent.com/64782528/178996895-26189310-b39d-4640-bb2b-15a1312f28f2.png)

**Comment by CarloNannings** [comment]
De linker (rood) is het pictogram voor Geboorde put met voordruk. Niet verwijderen dus.

**Comment by Oostjoost** [comment]
zorg eens voor uniformiteit in symboliek. Blauw is een geboorde put vanuit OIV en de rode een geboorde put vanuit natuurband ( staan er dus beide in) niet even op te lossen denk ik. Dit moet de werkgroep symbolen oppakken samen met natuurbrand werkgroep

**Comment by OIV-NL-QGIS** [comment]
Wij gan hier niets mee doen dit is voor de gebruikende aplicatie leverancier
