### ISSUE TITLE
Snapfunctie werkt niet goed

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#290]
Graag aandacht voor de snap-functie in het algemeen want QGIS crasht hierdoor regelmatig. 
Bijv. snappen aan BAG-laag lukt wel, snappen aan Bouwlaag eindigt vaak in een crash. (instellen via Project > Opties voor snappen...)
Het lijkt door de plugin te komen.

**Comment by Oostjoost** [comment]
Snappen van QGIS zelf wordt niet gebruikt door de plugin, in de plugin is een eigen snap-functie gebouwd

**Comment by CarloNannings** [comment]
De snapfunctie in de plugin werkt niet goed. Hij snapt o.a. niet/moeilijk bij een T-splitsing of kruispunt van lijnen. Soms crasht QGIS ook spontaan.

**Comment by Oostjoost** [comment]
Snappen op een T-splitsing kan ook niet. Snappen doe je aan een lijn of een punt. En bij een T-splitsing of een kruispunt zijn het 2 punten/lijnen van 2 verschillende objecten. Welke moet er dan worden gekozen?

**Comment by CarloNannings** [comment]
Volgens de beschrijving in QGIS moet je wel kunnen snappen op snijpunten:
https://docs.qgis.org/3.22/nl/docs/user_manual/working_with_vector/editing_geometry_attributes.html#snapping-and-digitizing-options

**Comment by Oostjoost** [comment]
De functie van QGIS wordt niet gebruikt voor het snappen. De plugin heeft een eigen snapfunctie.

**Comment by CarloNannings** [comment]
De snapfunctie werkt nog niet goed. Hij snapt lastig op de T-splitsingen en niet/nauwelijks op de kruisingen.

**Comment by CarloNannings** [comment]
Werkt wat ons betreft (nog steeds) niet naar behoren. Gesnapt wordt er alleen aan een rechte lijn.
Belangrijker vinden wij dat er gesnapt wordt aan een T- of kruispunt van lijnen. Soms, niet altijd, kan er gesnapt worden aan T-punten.

**Comment by Joachim-Tempelaars** [comment]
is aangepast en werk naar behoren
