### ISSUE TITLE
Volgorde historieregels omdraaien van nieuw naar oud

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#291]
Het is prettiger als de volgorde van de Historie regels van nieuw naar oud gaan. Dan heb je de meest recente direct boven in beeld. Nu moet je soms eerst naar beneden scrollen.

**Comment by Oostjoost** [comment]
![image](https://user-images.githubusercontent.com/23038880/184373176-97730825-eba2-4840-a7e4-276bf4e77551.png)

**Comment by Oostjoost** [comment]
Helaas vergeet hij de aangepaste sortering nadat het formulier weer is gesloten. Dit is iets van QGIS zelf en heb ik geen invloed op. Ik heb de weergave wel aangepast zodat alleen de datum wordt getoond.
