### ISSUE TITLE
Eenheden gevaarlijke stoffen

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#292]
In QGIS tabel "Gevaarlijke stoffen_eenheid" staat cilinder (opslagmedium) tussen de maateenheden (kg, stuk, m3).
Willen we ook de volgende opslagmedia toevoegen:
Drukhouder 
IBC 
Tank-ondergronds 
Tank-bovengronds 
Silo 
PGS-15 
Container 
Bunker 
Installatie 
Jerrycan 
Vat (60 liter - 120 liter - 200 liter) 
Kast 
Zak 
Palet

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.4.2-3.4.5.sql
resolves #292
