### ISSUE TITLE
Pictogram verdwijnt spontaan

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#293]
Als je vanuit 'Bouwlaag tekenen' op de knop [verplaatsen] klikt en vervolgens buiten de bouwlaag op een pictogram klikt en weer loslaat, verdwijnt het pictogram.
Pictogram verplaatst dan naar laatst positie waarop gewerkt werd.

**Comment by Oostjoost** [comment]
Niet reproduceerbaar

**Comment by CarloNannings** [comment]
Wiebe kan je dit eventueel laten zien. Pictogram wordt dan op een verkeerde positie geplaatst.

**Comment by Oostjoost** [comment]
Als hij een schermopname maakt dan is dat voldoende

**Comment by Oostjoost** [comment]
Na verslepen wordt de laatste positie blijkbaar onthouden. Na klikken springt de pictogram naar de laatst bekende locatie.
