### ISSUE TITLE
Voorstel aanpassen OIV menu structuur

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#299]
Bijgaand voorstel graag bespreken in het GitHub overleg. Indien iedereen akkoord is, is het voorstel om dit voor de versie 3.5.0 op de planning te zetten. Aanpassing is ingrijpend en kost 1-2 dagen.

[Voorstel OIV menus(2).pdf](https://github.com/OIV-NL-QGIS/QGIS_project/files/9316731/Voorstel.OIV.menus.2.pdf)

**Comment by OIV-NL-QGIS** [comment]
dit issue is gesloten we gaan verder in issue -> Wijzigingen n.a.v. gebruikersdag #348
