### ISSUE TITLE
Print functie in plugin aanpassen

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#300]
Graag de printfunctie aanpassen volgens bijgevoegd document.

[Printfunctie.docx](https://github.com/OIV-NL-QGIS/QGIS_project/files/9349321/Printfunctie.docx)

Printfunctie aanpassen

Op print aangeven:

1. 	Graag de objectnaam en/of “Blauwe I met objectnaam” printen
2. 	Lijst met gevaarlijke stoffen mee printen
3. 	In verband met versiebeheer graag printdatum vermelden op print

Aanpassingen op de print:

1. 	Graag mogelijkheid om zelf filenaam op te kunnen geven
2. 	Graag mogelijkheid om zelf de achtergrondkaart te bepalen
3. 	Graag mogelijkheid om zelf afdruk gebied te bepalen
4. 	Zelf kunnen bepalen welke lagen wel/niet mee geprint worden (aan/uit vinken)
5. 	Graag de lijn voor “hekwerk” zwart aangeven in de print. Grijs is nauwelijks te zien.

Fouten in printfunctie:

1. 	Indien je een geprint object (pdf) open hebt staan en nogmaals een print van hetzelfde object maakt komt er geen melding dat de file al in gebruik is. File wordt dan niet overschreven of vervangen.
2. 	Als je een map selecteert waar de print opgeslagen moet worden, maar op “Annuleren” drukt ipv op “Map selecteren” dan krijg je de melding dat de print gereed is. Gebeurd ook als je wel een map selecteert en dan op ”Annuleren” drukt. 
3. 	Je krijgt altijd een print van het object waar het I-tje aan gekoppeld is. Printen van individuele panden lukt niet.
4. 	Graag de roze )-punt vlakjes niet mee printen.

**Comment by Oostjoost** [comment]
Op print aangeven:

1.  Staat er al op bij de objecten print. Niet bij printen via de bouwlaag, maar een bouwlaag heeft geen directe relatie met een repressief object en dus een formelenaam. Deze heeft een relatie met een bag pand. Is dus ook niet bekend binnen de print.
2. Is reeds toegevoegd
3. Printdatum toegevoegd op alle prints

**Comment by Oostjoost** [comment]
Fouten in printfunctie:

1. Nog niet aangepast
2. Aangepast, Cancel/Annuleren wordt afgevangen
3. Dat kan met printen van bouwlaag
4. Die kunnen er nu niet vanaf worden gehaald. Dat zou best een ingrijpende aanpassing vergen in de styling van de kaartlagen.
