### ISSUE TITLE
Lijndikten aanpassen

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#301]
Graag de lijndikten van de scheidingen (Bouwlaag - Bouwkundige veiligheidsvoorzieningen) en de ruimten (Bouwlaag - Ruimten - Anders) standaard instellen op "Millimeters" ipv op "Kaarteenheden". Anders worden de lijnen bij inzoomen veel te dik weergegeven.

**Comment by Oostjoost** [comment]
De dikte van een lijn is zelf in de database in te stellen. Is dit niet voldoende? Het staat namelijk al jaar en dag op deze manier ingesteld. Dit houdt in dat iedereen mogelijk de dikte moet gaan aanpassen als we hem van kaarteenheid naar millimeter zetten.
Indien dit besproken is in het overleg, plan het dan ook even in als hij met 3.4.2. mee moet.

**Comment by Martijnjansenvrk** [comment]
@CarloNannings, misschien kan je dit gebruiken als workaround: 

![image](https://user-images.githubusercontent.com/67631279/187907712-0f7720db-b5a2-4ff2-809a-d683f5609ed8.png)
![image](https://user-images.githubusercontent.com/67631279/187907762-e6653819-fa91-4829-a62b-766b9c6ee5f3.png)
![image](https://user-images.githubusercontent.com/67631279/187907779-5720773f-ed54-49f5-b8d2-127f2bb8b615.png)
![image](https://user-images.githubusercontent.com/67631279/187907791-a32e6d2a-daf0-41a0-9c7d-6898bedc2b9f.png)
![image](https://user-images.githubusercontent.com/67631279/187907821-05f91a85-8831-485a-b3ba-80b603cb95c9.png)

Daarna het projectbestand opslaan, anders kan je elke keer weer deze aanpassingen doen.

**Comment by Oostjoost** [comment]
Wil iemand hier even een antwoord opgeven. Want het heeft dus meer gevolgen dan alleen even in QGIS de kaarteenheid aanpassen. En is elke regio het hier mee eens.

Een ander idee is om er een instelling van te maken, maar dit is best wel bewerkelijk. Het idee van Martijn is de manier waarop ik het dan ga aanpassen. Voor de gebruiker zelf is dit niet handig en ook niet wenselijk denk ik aangezien er dan binnen de regio verschillen ontstaan.

**Comment by Paulienv78** [comment]
Goedemorgen, Ik heb hier vanuit de vrf nog geen commentaar op gehad dat deze lijnen te dik zouden zijn. De lijndiktes passen we aan in de database.

**Comment by CarloNannings** [comment]
Wij gaan ook de lijndiktes aanpassen in de database. Issue kan wat mij betreft gesloten worden.
