### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#302]
Bijgevoegd als TXT-file ivm text-formatting in GitHub: [details.txt](https://github.com/OIV-NL-QGIS/QGIS_project/files/9452209/details.txt)

Komt naar voren zodra het project geopend wordt. Betreft een nieuwe schone QGIS installatie 3.22 LTR met release https://github.com/OIV-NL-QGIS/QGIS_project/releases/tag/v3.4.2_beta1

**Comment by Oostjoost** [comment]
Mogelijk een typo in een laagnaam

**Comment by Oostjoost** [comment]
Foutafhandeling toegevoegd indien er een lege lijst is. Dit zou eigenlijk niet voor mogen komen en ik kan het ook niet reproduceren, maar de melding komt als het goed is niet meer naar voren.

Is mogelijk het projectbestand zelf aangepast?
