### ISSUE TITLE
Soft-deleting werkt niet helemaal naar behoren

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#303]
Naar aanleiding van issue https://github.com/OIV-NL-QGIS/QGIS_project/issues/143 en aansluitend https://github.com/OIV-NL-QGIS/QGIS_project/issues/261 hebben we in de release [v3.4.2-beta1-Zaandam](https://github.com/OIV-NL-QGIS/QGIS_project/releases/tag/v3.4.2_beta1) nogmaals uitgebreid getest in QGIS 3.22. 

Het verwijderen middels soft-deleting van diverse symbolen/pictogrammen werkt goed, deze zijn eenvoudig terug te zetten, dus helemaal goed. Bouwlagen zelf zijn ook middels soft-deleting te verwijderen, dus ook dat is goed. 
Nu is het zoals eerder beschreven wel de wens om 'cascading' soft-deletes toe te passen, zoals je hebt gemaakt: https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.4.0-3.4.1.sql#L4

Als je nu een bouwlaag verwijderd, is deze weg. Maar de daaraan gekoppelde symboliek blijft staan. Dit moet dus nog cascading gebeuren, kan het zijn dat dat nog niet helemaal goed geïmplementeerd is?

**Comment by Oostjoost** [comment]
Ga ik even onderzoeken.

**Comment by Oostjoost** [comment]
Er zat een klein probleempje in de Trigger Functie. In het script voor 3.4.2 beta3 wordt dit opgelost. Graag even goed testen.
