### ISSUE TITLE
Rotatie symbolen

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#304]
Roteren van geplaatste symbolen werkt niet bij:

TAB algemeen:
- Brandweeringang
- Neveningang

 
TAB Toetreding en bereikbaarheid:
- Trappen
- Label Scenario

 
TAB Gevaren:
- Opslag stoffen

 
TAB BHV:
- Nooduitgang

 
TAB Bluswater:
- Bluswaterriool
- Open water
- Open water xxx zijde
- Bovengrondse brandkraan

 
TAB Natuur / POI:
- Inrijpunt

Betreft release [v3.4.2-beta1-Zaandam](https://github.com/OIV-NL-QGIS/QGIS_project/releases/tag/v3.4.2_beta1) op QGIS 3.22 LTR.

**Comment by vnogzwarta** [comment]
kleine aanvulling: betreft TAB Algemeen bij "terrein of gebied"

**Comment by Oostjoost** [comment]
Eerste analyse:

Het gaat om de complete lagen:

- Ingang ruimtelijk
- Scenario ruimtelijk

Gevaarlijk stoffen locatie ruimtelijk en alternatief bluswater zijn niet roteerbaar. Indien dit wel het geval moet zijn moet dit even als een aparte "wens/issue" worden aangemaakt. Dit is namelijk nog nooit zo geweest.

**Comment by Oostjoost** [comment]
Ik kan het niet direct verklaren. Moet ik even uitzoeken..

**Comment by Oostjoost** [comment]
1 database probleem en een default value in het QGIS project waren de veroorzaker

**Comment by ghost** [comment]
Het niet kunnen roteren van sommige symbolen is nog niet helemaal opgelost, een paar symbolen zijn te roteren maar onderstaande nog niet:

Bij “Terrein” kun je de volgende symbolen na plaatsen niet roteren: ( bij plaatsen zijn de symbolen wel te roteren maar zodra je na plaatsen nog iets wilt draaien gaat het symbool terug naar zijn originele positie)

TAB algemeen:
-	Brandweeringang
-	Neveningang

TAB Toetreding en bereikbaarheid:
-	Trappen

TAB Evenementen:
-	Nooduitgang

TAB Natuur / POI:
-	Inrijpunt
