### ISSUE TITLE
Overnemen bouwlaag inclusief symboliek

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#305]
Als je een nieuwe bouwlaag aanmaakt en deze overneemt van een andere bouwlaag en je neemt symboliek ook mee dan kun je deze pas bewerken (roteren/verwijderen/etc,) als eerst heel QGIS is afgesloten en opnieuw opgestart. Doe je dit niet dan krijg je bij selecteren de melding “dat de verkeerde bouwlaag is geselecteerd.

Betreft release [v3.4.2-beta1-Zaandam](https://github.com/OIV-NL-QGIS/QGIS_project/releases/tag/v3.4.2_beta1) op QGIS 3.22 LTR.

**Comment by Oostjoost** [comment]
Ik heb dit wel eerder gezien, echter kan ik het in mijn ontwikkelomgeving niet reproduceren. Hierdoor kan ik de oorzaak niet vinden. Kan iemand mij hiermee verder helpen, zodat ik kan onderzoeken wat het probleem is.

**Comment by vnogzwarta** [comment]
Het is op dit moment helaas niet verder te reproduceren dan alleen dat dit bij **Edit** voorkomt bij de knop "open  formulier van een object" en bij "delete object" .
QGIS helemaal afsluiten en dan opnieuw opstarten verhelpt dit issue.
