### ISSUE TITLE
NULL geometrie pythonmelding bij tekenen op bouwlagen

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/OIV_project#312]
Een van de planvormers kreeg de volgende melding tijdens het tekenen op een bouwlaag:

![image](https://user-images.githubusercontent.com/64782528/191551946-9599cf63-773c-4e13-a5a5-31cc9e7a47a5.png)

Er bleken in de db een aantal records zonder geometrie. Waarschijnlijk zijn er bouwlagen weggegooid via de puntenbewerkingstool. Dan maakt hij wel de geometrie leeg maar het record blijft bestaan.

Zou er iets in de db gemaakt kunnen worden dat zulke records niet meer voor kunnen komen?

**Comment by ghost** [comment]
https://github.com/OIV-NL-QGIS/QGIS_project/issues/131

**Comment by Oostjoost** [comment]
Voorstel is om op de lijn en vlak lagen een extra Check toe te voegen welke een restrictie zet op NULL geometrieën. Hierdoor kan de gebruiker nooit een "lege" geometrie opslaan en vang je het af bij de bron.

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.4.1-3.4.2-beta2.sql
resolves #312
