### ISSUE TITLE
Deels bouwlaag printen ipv gehele bouwlaag

### ISSUE THREAD

**Issue by Martijnjansenvrk** [OIV-NL-QGIS/OIV_project#313]
Bij het printen van een bouwlaag vanuit de plugin, wordt er maar een deel van de bouwlaag geprint ipv de gehele bouwlaag. 

Hieronder hoe het object eruit zit in Qgis
![object_in_qgis](https://user-images.githubusercontent.com/67631279/192996384-31a3a701-5c95-4b4c-bab4-ad02959c74cd.jpg)

Hier de bouwlaag waar het object aan gekoppeld is
![gekoppeld_bagpand](https://user-images.githubusercontent.com/67631279/192996393-efcec495-8786-4fd1-a2cf-91aae7dff846.jpg)

En hier hoe Qgis deze uitprint. 
[geprinte_object.pdf](https://github.com/OIV-NL-QGIS/QGIS_project/files/9673285/geprinte_object.pdf)

De plugin kijkt naar het bagpand ipv de bouwlaag tijdens het printen. Zie ook de bijlage. 
Graag dit zo maken dat bij het printen naar de bouwlaag wordt gekeken ipv het bagpand.

**Comment by Oostjoost** [comment]
Ik heb een eerste opzet gedaan naar het printen van een bouwlaag. Echter indien er meerdere bouwlagen zijn gekoppeld aan een pand zorgt dit ervoor dat er veel te veel wordt geprint. Zie dit extreme voorbeeld:

![image](https://user-images.githubusercontent.com/23038880/194157823-6d2a6635-8c75-4e0d-b39b-ebb968505c35.png)

**Comment by Oostjoost** [comment]
Ik hoor graag wat we hier als beste oplossing kunnen kiezen, ik denk dat er altijd uitzonderingen zijn.
Misschien moet er voor gekozen worden om het "terrein" waarop een bouwlaag staat als print grootte te kiezen. Maar bij een groot terrein kan dit ook zorgen voor rare prints.

Laatste optie is om bij uitzonderingen zelf te printen via de print-composer.

Graag specificeren hoe het dan moet werken en mijn voorstel is om hem uit deze versie vandaan te halen.

**Comment by Martijnjansenvrk** [comment]
Beste Joost, 

Een optie kan zijn dat de tekenaar zelf kan kiezen d.m.v. een pulldown wat er wordt geprint. Waarbij de keuze kan zijn welk gebied er geprint moeten worden en met wat voor buffer om dat vlak. (voorbeeld voorkeuzes: terrein, bouwlaag 15m, bouwlaag 50 meter). Door dit krijg je minder extremen zoals je boven aangeeft.

**Comment by Joachim-Tempelaars** [comment]
project vrnhn, vrf en vrk
