### ISSUE TITLE
Maken Script voor verwijderen NULL geometrie-en

### ISSUE THREAD

**Issue by Martijnjansenvrk** [OIV-NL-QGIS/OIV_project#314]
Sql script maken voor alle regio's om NULL geometrie-en te verwijderen.

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.4.1-3.4.2-beta2.sql

het script nog een keer runnen ruimt alle NULL geometrieën op en zet constraints op de geometrie kolom dat die controleert op soort geometrie en zorgt dat hij nooit NULL mag zijn.

resolves #314
