### ISSUE TITLE
Opstart QGIS duurt lang

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#315]
De opstart van QGIS duurt 1 minuut 38 seconden totdat de lagen voor 100% geladen zijn
Daarna duurt het nog ongeveer 2 minuten tot QGIS werkelijk opgestart is.
Ligt dit aan de plugin ?
Ik hoorde Bob Hulst hier ook al over.

**Comment by OIV-NL-QGIS** [comment]
Tijdens de opstart blijft QGIS lang hangen op de laag werkvoorraad bouwlaag vlak

**Comment by Oostjoost** [comment]
aanpassingen aan de print-layouts zorgt ervoor dat de laadtijd van het project aanzienlijk verhoogd is. In de laatste versie is er voor de gevaarlijke stoffen een ingewikkelde toevoeging gedaan aan de print-layout. Als ik de print-layouts uit het project verwijder scheelt dit aanzienlijk in laadtijd.

Graag ter overweging. Functionaliteit ten opzichte van performance.

https://gis.stackexchange.com/questions/325862/slow-loading-of-qgis-project

**Comment by OIV-NL-QGIS** [comment]
Joost is het mogelijk dat OIV direct opstart zonder print composerdeel?  en dat je die later van uit de plugin de composer kan starten met optie op welke , Natuur, WO, OIV,  enz  kan starten?
