### ISSUE TITLE
DXF import neemt 30 minuten lijn niet over

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/OIV_project#316]
DXF import neemt 30 minuten lijn niet over

Als je de mapping maak en de 30minuten lijn benoem als 30 minuten dan ga je daarna importeren volgens de module is de import geslaagd maar dat is hij niet helemaal je mis dan nog de 30 minuten lijnen.

**Comment by Oostjoost** [comment]
aanpassingen aan de print-layouts zorgt ervoor dat de laadtijd van het project aanzienlijk verhoogd is. In de laatste versie is er voor de gevaarlijke stoffen een ingewikkelde toevoeging gedaan aan de print-layout. Als ik de print-layouts uit het project verwijder scheelt dit aanzienlijk in laadtijd.

Graag ter overweging. Functionaliteit ten opzichte van performance.


https://gis.stackexchange.com/questions/325862/slow-loading-of-qgis-project

**Comment by Oostjoost** [comment]
Onduidelijke melding, bij de test bestanden werkt het gewoon om te importeren. ook de 30 min scheidingen. Zie afbeelding.

![image](https://user-images.githubusercontent.com/23038880/196812977-486d7b90-4c95-422d-b118-76200c03d2be.png)

**Comment by Oostjoost** [comment]
Als ik even verder kijk worden er bijvoorbeeld op de begane grond 6 geometrieën als ongeldig gegeven:
![image](https://user-images.githubusercontent.com/23038880/196815530-2e0721f2-0984-4ce2-bf66-671771ff7067.png)
