### ISSUE TITLE
PDOK geeft vaak fout melding dat je meer dan 50.000 punten bevraagd

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/OIV_project#317]
PDOK WFS bevraging geeft vaak fout melding dat je meer dan 50.000 punten bevraagd dit terwijl je alleen ben ingezoomd op je object.
In mijn test had ik maar max 20 panden in beeld en kreeg ik toch die melding.

Kan de PDOK bevraging beperkt worden tot de BoudingBOX van de viewer x / y van dat moment?

**Comment by Oostjoost** [comment]
Dit gaat niet opgelost kunnen worden voor de release van 3.4.2
Ik denk dat echt nieuwe issues voor een nieuwe versie zijn en niet voor een aankomende release.

**Comment by OIV-NL-QGIS** [comment]
Joost kan je  testen met een nog lager zoom nivo?

**Comment by Oostjoost** [comment]
Zoomniveau ingesteld op 1:1000 en lager ipv 1:5000 en lager
