### ISSUE TITLE
Info_of_interest later zichtbaar

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#322]
Tekenaars hebben "last van" de informatie mbt de waterkaarten.
Met name de laag info_of_interest - label. Deze graag standaard op een lager zoomniveau zichtbaar maken.

Of

Informatie mbt waterkaarten in een apart kopje "Waterongeval" onderbrengen zoals "Bouwlaag" "Bluswater" en "Repressief object".

**Comment by Oostjoost** [comment]
De labels voor de waterkaarten worden zichtbaar op een schaal van 1:30.000
Dit is voor alle lagen binnen repressief object niet anders. Mocht het lager zichtbaar moeten zijn, denk er dan even over na dat dit bijvoorbeeld gevolgen kan hebben voor het printen van natuurkaarten met een schaal van 1:25.000

De 2e oplossing is zeker geen optie aangezien ook een waterkaart een repressief object is en het volgens mij juist niet de bedoeling is om te gaan splitsen in soorten repressief object.

Willen jullie aangeven wat het zoom-niveau moet zijn waarop ze zichtbaar worden? Ik ben niet degene die dat moet bedenken.

**Comment by Oostjoost** [comment]
Voor ik hier wat mee kan doen, graag eerst even een antwoord op de vraag dan weet ik hoe ik het in moet richten.

**Comment by CarloNannings** [comment]
Laat het zoomniveau maar op dit niveau. Als dit inderdaad gevolgen heeft voor de natuurkaarten is het niet gewenst om het zoomniveau aan te passen.
