### ISSUE TITLE
Aanpassingen printen

### ISSUE THREAD

**Issue by Oostjoost** [OIV-NL-QGIS/OIV_project#325]
Aanpassingen op de print:

1. Graag mogelijkheid om zelf filenaam op te kunnen geven
2. Graag mogelijkheid om zelf de achtergrondkaart te bepalen
3. Graag mogelijkheid om zelf afdruk gebied te bepalen
4. Zelf kunnen bepalen welke lagen wel/niet mee geprint worden (aan/uit vinken)
5. Graag de lijn voor “hekwerk” zwart aangeven in de print. Grijs is nauwelijks te zien.
6. Graag de roze )-punt vlakjes niet mee printen.

**Comment by CarloNannings** [comment]
De datum notatie in QGIS en de print is anders:
- QGIS: jjjj-mm-dd
- Print: mm-dd-jjjj
Hier kunnen misverstanden over ontstaan

De matrixcode uit QGIS is niet hetzelfde als in de print (3 november 2022 wordt weergegeven als 11 maart 2022):
![image](https://user-images.githubusercontent.com/95032611/205906263-aa0e6ab9-3d31-4396-adee-2a8e27d75f02.png)

**Comment by Joachim-Tempelaars** [comment]
project vrnhn,  vrf en vrk

**Comment by CarloNannings** [comment]
[Printlayout voorstel A3.docx](https://github.com/user-attachments/files/17801054/Printlayout.voorstel.A3.docx)
[Printlayout voorstel A4.docx](https://github.com/user-attachments/files/17801056/Printlayout.voorstel.A4.docx)
