### ISSUE TITLE
Fouten in printfunctie

### ISSUE THREAD

**Issue by Oostjoost** [OIV-NL-QGIS/OIV_project#326]
Indien je een geprint object (pdf) open hebt staan en nogmaals een print van hetzelfde object maakt komt er geen melding dat de file al in gebruik is. File wordt dan niet overschreven of vervangen.

**Comment by Joachim-Tempelaars** [comment]
Project voor vrnhn en vrf

**Comment by Joachim-Tempelaars** [comment]
en vrk
