### ISSUE TITLE
BAG pand identificatie wordt niet gevuld

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/OIV_project#328]
Als je in  de QGIS plugin een pand aan klik in de BAG dan blijft de BAG pand identificatie vakken leeg.

Kan deze info nu aangevuld worden door de BAG info met de BAG API te bevragen en in vullen?

**Comment by Joachim-Tempelaars** [comment]
BAG pand identificatie bug meenemen bij ontwikkeling rondom BAG

**Comment by Oostjoost** [comment]
Bevraging BAG API is compleet verwijderd
