### ISSUE TITLE
BAG kaartlaag is verouderd

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#329]
De BAG kaartlaag 'BAG panden - database' is verouderd. Graag een nieuwe.
De "BAG panden PDOK" geeft een foutmelding. Mogelijk vanwege teveel data wat ingelezen moet worden.

**Comment by OIV-NL-QGIS** [comment]
Dit is voor je lokale GEO database beheerder om het te updaten
