### ISSUE TITLE
Foutmelding tijdens bewerken i

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/OIV_project#330]
i-tje moet niet bewerkbaar zijn vanuit de bouwlagen tekenen. 

Antwoord Joost->
Dat moet worden afgevangen, dat dat niet meer kan. 
Dan krijg je ook die foutmelding niet.

**Comment by Joachim-Tempelaars** [comment]
Bug oplossing mee nemen in nieuwe plugin layout
