### ISSUE TITLE
Historie is niet te verwijderen

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#333]
Historie is niet te verwijderen in de plugin.
In dit voorbeeld staan 2 records:
2022-11-25
2022-11-28
![gh2](https://user-images.githubusercontent.com/73171956/206421144-44785e2e-b79b-43b4-9f7f-d468c04e754d.png)

Zodra een van deze verwijderd wordt, klik je op opslaan en terug. Zodra je QGIS wilt afsluiten komt het volgende scherm naar voren, met daarin de vraag of het opgeslagen moet worden:
![gh3](https://user-images.githubusercontent.com/73171956/206421161-f5f449ce-b367-4e77-808e-933f6ded9bcc.png)

Vervolgens wordt dit niet opgeslagen zoals de knop 'opslaan en terug' en de daaropvolgende popup suggereert.

We gebruiken release https://github.com/OIV-NL-QGIS/QGIS_project/releases/tag/v3.4.2 i.c.m. QGIS 3.22.

**Comment by OIV-NL-QGIS** [comment]
Was deze al opgelost?
