### ISSUE TITLE
TypeObject in view_objectgegevens

### ISSUE THREAD

**Issue by Oostjoost** [OIV-NL-QGIS/OIV_project#334]

**Comment by OIV-NL-QGIS** [comment]
Wat is dit Joost?

**Comment by Oostjoost** [comment]
Vraag vanuit Friesland om bij elke view_ welke naar de voertuigen gaan het typeobject op te nemen in de view in verband met de styling.

Graag even laten weten of dit uitgevoerd moet worden

**Comment by ghost** [comment]
Zojuist besproken in het overleg. Het lijkt ons handiger deze views in je eigen regio te maken. Ben je flexibel in het aanpassen hiervan op ieder moment.
