### ISSUE TITLE
opentopokaart laag doet het niet meer.

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/OIV_project#335]
Het project start automatisch op met de Opentopo kaartlaag als achtergrond. Deze werkt niet meer. Zou in de volgende release dit aangepast kunnen worden?

![image](https://user-images.githubusercontent.com/64782528/210359668-96d0617a-6b16-4124-8a3a-abdba11dbc9d.png)

**Comment by CarloNannings** [comment]
Voor Open Topo moet per 1-1-2023 betaald worden.
Er wordt gezocht naar een alternatief.

**Comment by Joachim-Tempelaars** [comment]
Opentopo verwijderen.
Als er een nieuw alternatief komt wordt deze toegevoegd
