### ISSUE TITLE
Aanpassingen bluswater project

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#337]
Ik zou graag de volgende aanpassingen in het bluswaterproject willen doorvoeren:

•	Bij brandkraaninspectie:
o	Afgekeurd en ter reparatie --> aanpassen ‘t’ naar ‘true’ (of eigenlijk Ja)
o	Werkbaar en reparatie --> aanpassen ‘t’ naar ‘true’ (of eigenlijk Ja)
o	Toevoegen: (paars bolletje) reparatie gemeente uitgevoerd --> "conditie" = reparatie uitgevoerd
![image](https://user-images.githubusercontent.com/95032611/214837784-74a0db97-b7d3-4c2f-a076-b7928fd836e1.png)

•	De volgende vinkjes standaard zetten bij opstarten project:
o	Stavaza-per gemeente --> Uit
o	Brandkraaninspectie --> Aan
o	Waterleidingbedrijf --> Uit

•	Zichtbaar maken dat naar gemeente en/of PWN gemelde reparaties “over de datum zijn” om vinger aan de pols te houden over de voortgang.

•	Zoekfunctie om te zoeken op brandkraannummer zoals in Cogo.

•	Bij "Inspectie - object attributen" in brandkraan project staat bij "Conditie" de tekst inspecteren. Deze tekst graag weglaten. "Inspectie" staat al in het keuzemenu.
  
•	Foto uit Cogo app wordt niet zichtbaar bij “Brandkraaninspectie”.

•	Als in “QGIS Bluswater” een brandkraan van inspecteren naar werkbaar gezet wordt en vervolgens wordt deze doorgestuurd naar de gemeente, dan blijft de brandkraan donkerblauw in plaats van oranje. Het doormelden naar de gemeentelijke cogo-app functioneert in beide gevallen niet.

•	De bovengrondse brandkraan ontbreekt bij de alternatieve bluswatericonen.

**Comment by OIV-NL-QGIS** [comment]
Carlo,
Ik zou dit stuk graag even samen doornemen omdat wij Bluswater controle aan het bouwen zijn in Input/Mergin app

Mvg Bob

**Comment by OIV-NL-QGIS** [comment]
issue is verplaatst naar https://github.com/OIV-NL-QGIS/OIV_Bluswater/issues/1
