### ISSUE TITLE
Omschakelen naar testdatabase foutmelding

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/OIV_project#338]
![image](https://user-images.githubusercontent.com/64782528/217776550-33ac7ec4-6a18-4314-b650-0a08918ee193.png)

**Comment by ghost** [comment]
Dit is bij ons opgelost door het bestand `C:\Program Files\QGIS 3.22\apps\qgis-ltr\python\plugins\oiv\config_files\plugin_settings.json` ook schrijfrechten te geven aan zowel de Administrator- als Gebruikersgroep.
