### ISSUE TITLE
5c_schema_waterongevallen.sql ontbreekt in de scripts voor het aanmaken van de schema's

### ISSUE THREAD

**Issue by Geoneer** [OIV-NL-QGIS/OIV_project#339]
**Beschrijf de bug - kort en duidelijk**
5c_schema_waterongevallen.sql script ontbreekt. 

**Hoe te reproduceren**
Beschrijf de stappen hoe de bug te reproduceren is:
1. '...' Volg de handleiding met de scripts 1 .. n. 
2. '...'
3. 

**Stapelspoor**
Maak waar mogelijk een screenshot van het stapelspoor

**Wat wordt er verwacht**
Beschrijf kort en duidelijk welk gedrag er wordt verwacht van de applicatie

Gebruiker wordt verzocht tijdens de inrichting van de database het script [5c_schema_waterongevallen.sql] te openen en te draaien. Deze staat niet in de map:
![afbeelding](https://user-images.githubusercontent.com/218929/219173740-c9524888-9dde-410b-9571-2129bacab486.png)

**Screenshots**
Indien van toepassing voeg screenshots of een filmpje toe.

**Op welk device kwam de issue naar voren** - niet relevant. Is voor de database configuratie relevant. Niet voor QGIS. 
 - Besturingssysteem en versie: 
 - QGis versie:
 - Database connectie of WFS connectie:
 - Welke versie van Postgres/PostGis:
 - Welke versie van GeoServer:

**Wilt u verder nog wat opmerken**

**Comment by Martijnjansenvrk** [comment]
Beste Geoneer, 
Dit script is komen te vervallen door het schema waterongevallen binnen het schema objecten te zetten.  
De wiki pagina met de installatie beschrijving loopt nog achter. 
Dus als je dit script overslaat en verder gaat met script 6a dan moet alles goedkomen.
