### ISSUE TITLE
Melding kaartlagen na nieuwe installatie

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#340]
![qgis](https://user-images.githubusercontent.com/73171956/220287908-7cc747bb-185f-4f4f-a895-13aa063027b1.png)

Betreft plugin versie: https://github.com/OIV-NL-QGIS/QGIS_project/releases/tag/v3.4.03
Betreft QGIS versie: 3.22.16-Białowieża

**Comment by Oostjoost** [comment]
- Kladblok was een probeersel en is uit het project verwijderd
- Openbasiskaart ging fout omdat een http - URL werd gebruikt ipv https. Dat is als het goed is opgelost. Dus de openbasiskaart is gewoon te gebruiken vanaf de nieuwe versie
- Werkvoorraad label is opgenomen in het project (2x)
[#aa5ec60 ](https://github.com/OIV-NL-QGIS/QGIS_project/commit/aa5ec60db6ebcf9e17dd61140e8d1b6ae76de760) resolves #340
