### ISSUE TITLE
QGIS loopt vast

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#341]
Na het opstarten is een nieuw terrein aangemaakt, daar is een bouwlaag aan gemaakt en symboliek geplaatst. Toen liep QGIS vast (popup met reageert niet). 
Daarna QGIS opnieuw opgestart en bleef dit probleem. Je kan dan geen terrein, bouwlaag of symboliek selecteren. Na 6 keer opnieuw opstarten werkt het wel weer en daarna hetzelfde probleem weer. 
De plugin window is wel te selecteren, maar vervolgens kun je geen terrein of bouwlaag selecteren. Je ziet de muis wel hoveren over de kaart, maar zodra je een selectie maakt loopt deze vast. Geen waarschuwingen of Python errors zichtbaar. 

Betreft plugin versie: https://github.com/OIV-NL-QGIS/QGIS_project/releases/tag/v3.4.03
Betreft QGIS versie: 3.22.16-Białowieża. Nieuw geïnstalleerd.

**Comment by Oostjoost** [comment]
Is dit te reproduceren? Ik krijg het niet voor elkaar. Anderen die die ook ervaren?

**Comment by Joachim-Tempelaars** [comment]
Testen in nieuwe versie

**Comment by Oostjoost** [comment]
Geen actie vanuit mij, dus ik meld hem af. Alle issues die gesloten worden moeten worden getest.
