### ISSUE TITLE
Wijzigingen n.a.v. gebruikersdag

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#348]
### **Graag vooraf eerst een indicatie van de kosten voordat werkzaamheden opgepakt worden.**

- [x] Taak1, 2, 4 en 8: Weinig tot geen impact, inschatting is 1 uur
Alhoewel ik taak 1 zonde vindt van de ruimte.
- [x] Taak 3: Graag een tabel in welk stadium welke tekst moet worden weergegeven, aangezien dit was gespecificeerd door NHN. Inschatting 2 uur, afhankelijk van hoe vaak het moet worden aangepast.
- [x] Taak 5: Advies om dit niet te doen, de CAD-functionaliteiten worden geopend bovenin net als bij het tekenen van vlakken en lijnen. Dit geeft uniformiteit omdat het altijd op dezelfde plek te vinden is.
- [x] Taak 5a: Verwijderen van het terrein moet nog terug worden gezet. Info en Pan waren overbodig. Inschatting 2 uur

- [x] Taak 7: Lijkt of hij niet zijn formulier ververst of opnieuw initialiseert, dit is een bug.  Inschatting 2 uur

- [x] Taak 10: Onderzoek nodig

Sowieso is dit natuurlijk totaal niet handig om op deze manier aan te maken. Als ik ontwikkel ontwikkel ik per punt en nu zijn er 11 taken in één issue aangemaakt. Sommige zijn bugs, de meeste zijn wensen. 

**Taak 1.** Toevoegen aan tabblad: tekst 'Terrein' en 'Bouwlaag' boven dit pictogram:
![gh01](https://user-images.githubusercontent.com/73171956/227894338-1eb6a6a0-e3a9-42c5-8b31-45b394df1c4e.png)

**Taak 2.** Labels wijzigen
Tekst 'Info BAG' en 'Info BGT' hernoemen naar: 'Terugmelding BAG' en 'Terugmelding BGT'
![gh02](https://user-images.githubusercontent.com/73171956/227894625-fb1c0b47-67c7-45ee-8b62-607c68762369.png)

**Taak 3.** Beschrijving verduidelijken
De rood onderstreepte tekst verduidelijken dat je hier ofwel nieuwe zaken mee kan tekenen of bestaande mee kan bewerken.
![gh03](https://user-images.githubusercontent.com/73171956/227895518-21f5c427-c218-438e-89e5-4cea68942482.png)
![gh04](https://user-images.githubusercontent.com/73171956/227895537-1c1603b1-6d00-407d-88c0-37e454d7f0cf.png)

**Taak 4.** Label 'Info of Interest' aanpassen naar 'Losse attributen'
![gh05](https://user-images.githubusercontent.com/73171956/227896029-3bd935f0-3511-4ba5-a6cf-5c37f8903b16.png)

**Taak 5.** Oude symbolen van toevoegen terrein terugzetten
![gh09](https://user-images.githubusercontent.com/73171956/227925917-bb6c60fe-0a12-438d-a6bf-0437b6e9dde6.png)

**Taak 6.** Geometrie-vlak aanpassen via OIV plugin
De puntenbewerker van QGIS willen gebruikers toepassen voor o.a. het bewerken van de bouwlagen, het terrein etc. Kan in de UI van de OIV plugin de puntenbewerker aangeklikt worden? 

**Taak 7.** Bij het tekenen van een nieuw object laat het grijze veld de naam van het vorige object zien bij het veld 'Repressief object'.

**Taak 8.** Selectie-veld bouwlaag is niet leesbaar (geselecteerde waarde was eerst wit-blauw, nu wit-wit):
![gh08](https://user-images.githubusercontent.com/73171956/227921996-ebda6f2b-6621-4d0b-b45e-9746c38d625d.png)

**Taak 9.** Werkvoorraad optionele module maken
Een aantal regio's gebruiken de werkvoorraad helemaal niet, en willen juist ook zaken via de ingebouwde tekentools bewerken . Het idee is dat de werkvoorraad los staat van het project, zoals bv. bluswater ook niet geinstalleerd hoeft te worden. Daarmee heb je de mogelijkheid om de ingebouwde tekentools te gebruiken zonder werkvoorraad-processen. 

**Taak 10.** Bug in de werkvoorraad: als je een object wilt verwijderen moet je eerst het hele object afpellen qua symbolen en bouwlagen voordat je het object zelf verwijderd. Anders kun je de werkvoorraad niet bewerken omdat het object er niet meer is. 

Daarnaast is nog een aandachtspunt om aangepaste resoluties te ondersteunen. Onze tekenaars werken met 2K resoluties en dan ziet de nieuwe interface er minder bruikbaar uit. O.a. de pictogrammen voor de knoppen.

**Comment by Oostjoost** [comment]
Zie bijgevoegd in de issue mijn opmerkingen en inschattingen

**Comment by OIV-NL-QGIS** [comment]
In overleg met het OIV github team gaan we taak 6 even parkeren richting een instructie filmpje.
Taak 11 is er uit gehaald en een apart issue van gemaakt

**Comment by ghost** [comment]
Graag zorgen dat de nieuwe UI goed mee schaalt bij hogere resoluties. Zie ook https://github.com/OIV-NL-QGIS/QGIS_project/issues/150. Gaat niet alleen om symbologie in de plugin maar ook teksten e.d.

**Comment by Oostjoost** [comment]
Taak 6: Advies om dit niet te doen, ik kan alleen een knopje maken om de node-tool aan te roepen van QGIS zelf. Daarna zal de gebruiker altijd nog op opslaan moeten klikken. Dit zou via OIV kunnen maar niet geautomatiseerd. Ik kan niet afvangen wanneer een gebruiker klaar is met bewerken, dus dit zal een handmatige actie in zich blijven houden. Inschatting 4 uur.

Taak 6 wordt niet gedaan

**Comment by Oostjoost** [comment]
Taak 9: Ingebouwde tekentools zijn te gebruiken behalve verwijderen. Dit is een known issue. https://github.com/OIV-NL-QGIS/QGIS_project/issues/200 
Niet van toepassing voor deze taken of dit issue. Werkvoorraad is vooral een database iets, om OIV wel toegang te geven direct tot de database maar 3e applicaties niet. Uitschakelen of verbergen in de interface is dan de beste optie om OIV niet beschikbaar te maken, maar dan moet #200 wel zijn opgelost. Inschatting 4 tot 8 uur

Taak 9 vervalt, ivm duplicaat #200

**Comment by Joachim-Tempelaars** [comment]
Taak 10 testen vanuit plug-in

**Comment by Joachim-Tempelaars** [comment]
2K resoluties wordt meegenomen in versie 3.5.01

**Comment by Oostjoost** [comment]
CAD functies bij het tekenen van een terrein worden bovenin weergegeven
Taak 5

![image](https://user-images.githubusercontent.com/23038880/231797654-748470be-f41d-455b-a7c6-6e353aec2f03.png)

**Comment by Oostjoost** [comment]
![image](https://user-images.githubusercontent.com/23038880/232066727-dec09ee8-dff0-4468-a287-a6d9ae4b4575.png)
Taak 5a - verwijderen terrein

**Comment by ghost** [comment]
Wat is de status van het ontkoppelen/uitschakelbaar maken van de werkvoorraad? In release https://github.com/OIV-NL-QGIS/QGIS_project/releases/tag/v3.5.0-beta1 speelt dit:
![PHOTO-2023-05-15-15-28-51](https://github.com/OIV-NL-QGIS/QGIS_project/assets/73171956/16bf911e-eba6-41df-bbc3-90cb3089213e)

**Comment by Oostjoost** [comment]
Voor het laatste punt... overgenomen naar:
https://github.com/OIV-NL-QGIS/QGIS_project/issues/385

Daarmee kan dit issue worden gesloten
