### ISSUE TITLE
alles van een object in 1 keer te kunnen roteren/verplaatsen 

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/OIV_project#349]
Wens om alles van een object in 1 keer te kunnen roteren/verplaatsen (bv. nadat de BAG contouren ingemeten zijn en je het hele project een meter op wilt schuiven).

**Comment by Oostjoost** [comment]
Inschatting om dit te ontwikkelen is 8u. Er moet best wat aangepast worden om een multiedit aan te maken. Het kan meevallen, maar dit is mijn eerste inschatting. Eigenlijk hetzelfde als de multi-delete. Mogelijk wel te combineren in 1 ontwikkeling. Maar dat moet gaande weg blijken.

**Comment by OIV-NL-QGIS** [comment]
Project goed uitschrijven met verwachtingen met hoe en wat en wanneer

**Comment by vnogzwarta** [comment]
De wens is om PER BOUWLAAG alles te kunnen selecteren om te roteren/verplaatsen.
Stel dat de definitief ingemeten BAG contouren wezenlijk anders liggen dan de tijdelijke contouren dan is het wenselijk om alles in 1 keer te kunnen roteren en of verplaatsen.
- Dus via een selectietool een selectie maken van de totale bouwlaag. (vlak van de betreffende bouwlaag/puntsymbolen/lijnsymbolen en vlakken).
- Keuze kunnen maken van verplaatsen/roteren.
Een hulplijn zoals deze ook bij het verplaatsen/roteren van puntsymbolen aanwezig is is hierbij wenselijk.
Graag bekijken of en hoe dit eventueel te realiseren is.

**Comment by Oostjoost** [comment]
Ik zie dit eigenlijk als 4 verschillende functionaliteiten:

1. Verplaatsen van alles binnen een selectie polygoon
https://github.com/user-attachments/assets/2050c627-4673-4201-93f1-2a7904814382
2. Roteren van alles binnen een selectie polygoon volgens dezelfde rotatie
https://github.com/user-attachments/assets/2050c627-4673-4201-93f1-2a7904814382

3. Verplaatsen van een hele bouwlaag, inclusief inhoud
![image](https://github.com/user-attachments/assets/157be6ac-48c5-4907-af2a-347ba9dcaf32)

4. Roteren van een hele bouwlaag - om de centroide van de bouwlaag
![image](https://github.com/user-attachments/assets/d2167923-f99e-4570-9716-1a4c47480d95)
