### ISSUE TITLE
Fout bij aanmaken nieuw terrein 

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#358]
Bij aanmaken **nieuw** terrein dient ergens op de BGT geklikt te worden.
Echter kun je ook op een roze BAG vlak klikken zonder foutmelding.
Is volgens ons niet de bedoeling.

**Comment by Oostjoost** [comment]
Dit is altijd al zo geweest, je kunt een terrein ook koppelen aan een pand, dit zou een nieuwe werkwijze worden en werkflow binnen de plugin. Dit zou ook betekenen dat er een update zou moeten plaatsvinden aan alle bestaande databases om dat er nu in het veld "basisreg_identifier" ook een BAG-ID kan staan. Als dit gewenst prima, maar lijkt mij niet verstandig om in een release versie uit te geven zonder testen.

Voor nu ontkoppel ik hem van deze milestone.

**Comment by CarloNannings** [comment]
Oke. gaan we bespreken in het GitHub overleg.
