### ISSUE TITLE
Foutmelding bij opstarten

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#359]
QGIS start op met de volgende foutmeldingen:

![image](https://user-images.githubusercontent.com/95032611/235107358-7ec655ce-01c5-4a3e-9dfc-be2b74b241a9.png)

![image](https://user-images.githubusercontent.com/95032611/235107388-ff3b261c-ed0d-410e-b705-df65f35d0678.png)

**Comment by ghost** [comment]
Wat staat er onder het veld 'Verbinding certificaten'? service.pdok.nl heeft geen self-signed cert, dus dat is bijzonder. Kan ook intern een issue zijn

**Comment by CarloNannings** [comment]
![SSL fout](https://user-images.githubusercontent.com/95032611/236790055-4482aa68-4381-4d5c-9c68-af020c9b25f8.PNG)

**Comment by Oostjoost** [comment]
Dit heeft in principe niet met OIV te maken. Je zult zelf het certificaat moeten installeren. Je kunt ook de uitzondering opslaan.
