### ISSUE TITLE
Tekst repressief object kan aangepast worden

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#360]
Na klikken op de knop [Toevoegen] kan de naam van het repressief object aangepast worden.
Is volgens ons niet de bedoeling. Graag wijzigen in alleen lezen.

![image](https://user-images.githubusercontent.com/95032611/235108058-5fddc05b-7ed2-48a1-a9f6-df67160f4229.png)

**Comment by OIV-NL-QGIS** [comment]
Het invoer veld waar nu brandweer kazerne staan gewoon normale grijze kleur van maken

**Comment by Oostjoost** [comment]
Geldt ook voor het veld "Bag pand identificatie" Beide maak ik niet bewerkbaar
