### ISSUE TITLE
Terrein toevoegen

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#363]
Als er bij een object al een terrein is toegevoegd, is het mogelijk om nog een tweede terrein aan te maken (“Terrein toevoegen is nog actief”).
-	Is het gewenst/noodzakelijk om een tweede terrein toe te voegen?
-	Is het mogelijk te bepalen dat er voor een object wel/niet een Terrein aangemaakt is en de status van deze knop daarop af te stemmen?
-	Graag oude pictogram weer terug zetten. 

![image](https://user-images.githubusercontent.com/95032611/236444834-46a654dd-1618-4fcc-a17d-0d0ff261bc64.png)

**Comment by Oostjoost** [comment]
Is altijd al mogelijk geweest om meerdere terreinen toe te voegen aan een object.

**Comment by CarloNannings** [comment]
Is dat gewenst?

**Comment by OIV-NL-QGIS** [comment]
Joost graag Graag oude pictogram weer terug zetten.
