### ISSUE TITLE
Afsluitknoppen standaardiseren.

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#364]
Algemeen punt ten aanzien van de ‘afsluit’ knoppen [Terug] in de menu’s (Terrein en Bouwlaag):

![image](https://user-images.githubusercontent.com/95032611/236445053-eeccfcb4-12bc-4024-aada-ff8d0b38c445.png)

Onder de knop [Toevoegen] staat de “afsluitknop” onderaan met de tekst ‘Terug’.
Onder de knop [Tekenen] staat de “afsluitknop” bovenaan met de tekst ‘Terug’.
Onder de knop [Info] staat de “afsluitknop” bovenaan met de tekst ‘Opslaan en terug’.

Graag deze knop op een vaste plek positioneren, bij voorkeur bovenaan, tekst: ‘Terug’.
Dus vet en zonder ‘Opslaan en’. Dat laatste is overbodig te vermelden en is ook een beetje vreemd als je een scherm sluit zonder iets gewijzigd te hebben.

**Comment by Oostjoost** [comment]
De knop "Opslaan en terug" is daadwerkelijk opslaan en terug. Voor de anderen heb ik de knop bovenaan gezet en is het wel de functie "Terug"
