### ISSUE TITLE
Tekst die bij opmerking gevaren symbool wordt niet opgeslagen.

### ISSUE THREAD

**Issue by APostmaVRF** [OIV-NL-QGIS/OIV_project#370]
Als ik een gevaren symbool heb geplaatst en daar via het i'tje een opmerking aan toe wil voegen wordt deze niet opgeslagen.
Dit bij meerdere gevaren symbolen geprobeerd en daar het zelfde probleem.

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.4.5-3.5.0.sql
resolves #370
