### ISSUE TITLE
werkt de Printoptie V3.5.0 Hoorn al?

### ISSUE THREAD

**Issue by Frankvrzw** [OIV-NL-QGIS/OIV_project#371]
werkt de Printoptie V3.5.0 Hoorn al?

**Comment by OIV-NL-QGIS** [comment]
Frank gaat dit punt nog aanvullen

**Comment by Oostjoost** [comment]
Dit issue kan niet meer mee met 3.5.00
Morgen is de release en er is nog niets aangevuld.

**Comment by OIV-NL-QGIS** [comment]
Ik heb Paulien gesproken dit werkt gewoon. (als je hem "normaal"installeer op een niet gesplitste kantoor omgeving.

**Comment by Frankvrzw** [comment]
Printversie werkt hier ook, al heeft de computer er wel moeite mee. Hij lijkt vast te lopen maar na enkele minuten staan de printjes in de map.
