### ISSUE TITLE
macro's starten niet op bij opstarten

### ISSUE THREAD

**Issue by Frankvrzw** [OIV-NL-QGIS/OIV_project#372]
Tijdens het opstarten van de nieuwe testversie (Hoorn) laden de macros niet

**Stapelspoor**
Maak waar mogelijk een screenshot van het stapelspoor

**Wat wordt er verwacht**
Beschrijf kort en duidelijk welk gedrag er wordt verwacht van de applicatie

**Screenshots**
Indien van toepassing voeg screenshots of een filmpje toe.
![geen macros](https://github.com/OIV-NL-QGIS/QGIS_project/assets/134381329/2f406228-d80f-40ae-b066-d5394a0cc114)

**Op welk device kwam de issue naar voren**
 - Besturingssysteem en versie: 
 - QGis versie:
 - Database connectie of WFS connectie:
 - Welke versie van Postgres/PostGis:
 - Welke versie van GeoServer:

**Wilt u verder nog wat opmerken**

**Comment by Oostjoost** [comment]
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/23038880/0891ef80-bfb9-4db4-b8e0-40765ba23f83)

Dit is een instelling in QGIS die gedaan moet worden na een nieuwe installatie van QGIS. Zie het screenshot waar je de instelling kunt doen in het menu ->
Extra - Opties - Algemeen

**Comment by Frankvrzw** [comment]
gedaan thanks voor het snelle antwoord
