### ISSUE TITLE
Als ik in het terrein een donut knip(ring toevoeg) en maak hier een nieuw terrein in is deze dan los gekoppeld van het omringende terrein?

### ISSUE THREAD

**Issue by Frankvrzw** [OIV-NL-QGIS/OIV_project#374]
@Oostjoost Als ik in het terrein een donut knip( ring toevoeg) en maak hier een nieuw terrein in is deze dan los gekoppeld van het omringende terrein?
Of kijkt de qgis plugin allen naar de buitenste punten?

**Wilt u verder nog wat opmerken**
![terrein in terrein](https://github.com/OIV-NL-QGIS/QGIS_project/assets/134381329/845490c4-6358-40e0-a766-58cf03680361)
![terrein in terrein test](https://github.com/OIV-NL-QGIS/QGIS_project/assets/134381329/003a0ca3-e9d9-4d29-9682-203b5fa9efa6)

**Comment by Oostjoost** [comment]
Ja, die veronderstelling is helemaal juist. Dat is dan een losstaand terrein. Let wel even op dat je hem aan het juiste object koppelt
