### ISSUE TITLE
Testen 3.5.00 Beta2 . Lege regels bij invullen historie

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/OIV_project#376]
Als je bij terrein klikt op het infoveld en daarna de historie wil aanpassen dan geeft de geselecteerde regel geen tekst aan.

![Afbeelding van WhatsApp op 2023-06-05 om 10 08 23](https://github.com/OIV-NL-QGIS/QGIS_project/assets/64782528/e59203ef-0a89-4076-a7f3-b9dd730fc93d)

**Comment by Oostjoost** [comment]
De tekst is blijkbaar wit. Want er staat wel wat toch?

**Comment by Oostjoost** [comment]
Ik kan niets anders aanpassen aan de configuratie van QGIS om dit anders te laten zien. Of we moeten alle formulieren weer zelf gaan maken en daar waren we een aantal versies terug vanaf gestapt omdat dat veel beheer scheelt. Ik kan alleen de achtergrondkleur van het formulier aanpassen waardoor de "witte" tekst beter leesbaar wordt.

![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/23038880/17adb461-9023-493e-bc96-5aaae239c4fe)

Kunnen jullie je vinden in deze oplossing?

**Comment by Oostjoost** [comment]
Teruggezet en even voor de werkgroep. Ik kan de standaard instelling "witte" tekst niet omzeilen en het lijk ook nog afhankelijk van de stijl die onder Extra-opties-alegmeen is ingesteld en mogelijk zelfs versie afhankelijk.

**Comment by CarloNannings** [comment]
Dit treed bij (bijna) alle selectievelden op.
Mogelijk kan de selectieregel gekleurd (blauw) worden zoals het was.
