### ISSUE TITLE
test 3.5.00 Beta2: Bij terrein bouwlaag aangeven geeft rare waarde

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/OIV_project#377]
Bij de knop info -> objectgegevens 

Wanneer een gebruiker op de pijltjes- klikt bij de velden minimale en maximale bouwlaag dan komt daar een vreemde cijferwaarde te staan. 
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/64782528/93f56989-dab7-4040-a075-e324e22d48c5)

Die is wel handmatig aan te passen.
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/64782528/a284a777-d057-4b7f-b523-1af2ec7357a6)

Zou de vreemde cijferwaarde weg kunnen? Als het per ongeluk zo opgeslagen worden hebben we opeens heel veel bouwlagen

**Comment by Oostjoost** [comment]
Als het goed is geeft hij standaard een "lege" waarde. Ik heb nu de invoer beperkt van -10 tot 100.
