### ISSUE TITLE
Testen 3.5.00 Beta2: Losse symbolen

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/OIV_project#378]
Bij het beginscherm-> losse symbolen

![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/64782528/dc6b676a-9853-4700-a5cc-9528f742ecc3)
De symbolen bij alternatieve bluswatervoorziening zijn zichtbaar, de overige symbolen zijn niet zichtbaar na plaatsing. Er komt geen foutmelding.

**Comment by Paulienv78** [comment]
Als toevoeging: Symbolen staan wel in de tabel info of intersest - points
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/64782528/1a0aa7f8-15ce-4d89-9b5e-9d2ad9698c25)
info of interest - labels
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/64782528/fdef01bc-e09a-4cf9-bd3f-df99e21f4c6d)
info of interest - lines
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/64782528/7a9bdbaf-c7b1-4997-8c8d-d4842f256612)

**Comment by Oostjoost** [comment]
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/23038880/cbfb412b-89e9-4290-b78c-5b9d9fd02993)

Default staat de laag info_of_interest uit op basis van de wens van NHN in één van de vorige versies
