### ISSUE TITLE
Testen 3.5.00 Beta2: Printen bouwlagen-info stoffen mist

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/OIV_project#379]
Bij bouwlagen printen schrijft ie de pdf goed weg naar de opgegeven locatie. 
Bij het gevaarlijke stoffenbord welke op de eerste bouwlaag geplaatst is, is er extra info meegegeven maar dit staat niet op de print toegevoegd.
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/64782528/1169a0dd-065d-47a8-8f09-8bb6fb76a4a5)
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/64782528/16fbc3d7-9019-499d-87a4-76159597e319)
Schadecircel wordt wel toegevoegd
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/64782528/7160cba7-4915-4bda-bf94-70aeb9602b95)
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/64782528/f6bda966-df0a-480c-8859-b7ea0dfad560)

**Comment by Oostjoost** [comment]
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/23038880/d9e26097-b09f-4f02-9a1a-ab7a06c2e317)

**Comment by Oostjoost** [comment]
Vorige keer opgelost, echter denk dat ik hem vergeten ben op te slaan als sjabloon. Zou nu goed moeten werken
