### ISSUE TITLE
Test 3.5.00 Beta2: Tekenen terrein- opslag stoffen-foutmelding

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/OIV_project#380]
terrein->tekenen-> opslag stoffen.
Bij het invullen van de schadecirkel geeft qgis een postgisfout.

![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/64782528/5b0e90b0-f366-45ba-8666-b5cc1f50e9e1)

**Comment by Oostjoost** [comment]
Known issue - of eigenlijk gebruikersfout. Eerst opslaan van de stof, dan krijgt de stof een identifier, welke nodig is voor het opslaan van een schadecirkel. Dit is al een jaar of 8 zo.
