### ISSUE TITLE
Testen 3.5.0 Historie niet goed in te vullen

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#383]
Bij het aanmaken van een nieuwe historie regel komt hij direct in "EDIT modus" is het niet mogelijk de velden Behandeld en Afgehandeld in te vullen (naam te selecteren). Daardoor wordt de knop [Ok] niet actief en is er dus geen nieuwe Historie regel aan te maken.

![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/95032611/56020d73-b2e7-49b6-a534-3a7d2ce66ab3)

**Comment by Paulienv78** [comment]
Deze melding heb ik niet gekregen.

**Comment by Oostjoost** [comment]
Ik kan deze ook niet reproduceren. Ik zie ook geen juiste waarden (3) terugkomen om op te slaan. Dit betreft zo te zien een ongeldige waarde, je zult een nieuwe waarde moeten selecteren uit de dropdown.

Ik vermoed dat de waarde die er nu staat als id verwijst naar een teamlid die niet meer actief is. In de database bestaat de juiste persoon nog wel, alleen is hij bij een aanpassing in OIV niet meer te selecteren.
