### ISSUE TITLE
Wat is de status van het ontkoppelen/uitschakelbaar maken van de werkvoorraad?

### ISSUE THREAD

**Issue by Oostjoost** [OIV-NL-QGIS/OIV_project#385]
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/23038880/b5ea6443-17cb-4ccd-94a6-88bbf0dd4ffb)

Overgenomen van:
https://github.com/OIV-NL-QGIS/QGIS_project/issues/348

**Comment by Oostjoost** [comment]
Voor ik hier iets mee kan, hoor ik graag wat er moet gebeuren

**Comment by ghost** [comment]
Zojuist besproken, Joost gaat een database script beschikbaar stellen waarmee het verwijderen van objecten via de standaard QGIS tooling mogelijk is om de werkvoorraad te passeren. Database structuur blijft dan gewoon bestaan, de regio's die geen werkvoorraad gebruiken runnen die queries en de andere regio's hoeven niets te doen en blijft het functioneren zoals het nu werkt.

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.5.00-3.5.01.sql

In dit script wordt het mobiele schema aangemaakt. Dit zorgt ervoor dat de lagen bestaan en dat de gebruiker geen melding krijgt. Of je het nu wel of niet gebruikt.

Het verwijderen van objecten via de standaard QGIS tooling lijkt nog niet zo makkelijk, tenzij ik het gewoon "open" zet. Dus regio's die geen mobiel gebruiken kunnen dan te allen tijden verwijderen via de tooling.

**Comment by Oostjoost** [comment]
Willen jullie even kijken of de volgende oplossing werkbaar is om te deleten als je geen Mobiel gebruikt?

https://github.com/OIV-NL-QGIS/QGIS_project/assets/23038880/d5805521-6a79-4d39-96c6-da9748854696

Zo ja, dan ga ik dit doorvoeren in de database en is er geen installatie voor nodig.

**Comment by ghost** [comment]
Hallo Joost, dit is een wenselijke oplossing. Daarmee zou het in- en uitschakelbaar worden en da's precies wat we willen. Dank!

**Comment by Oostjoost** [comment]
In dit script wordt het opgelost:
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.5.00-3.5.01.sql
