### ISSUE TITLE
View objecten.schade_cirkel_calc toont verwijderde schadecirkels.

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/OIV_project#389]
Database view objecten.schade_cirkel_calc toont alle rijen uit objecten.gevaarlijkestof_schade_cirkel, ook als het veld datum_verwijderd is gevuld.

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.5.00-3.5.01.sql
resolves #389
