### ISSUE TITLE
Bouwlaag zelf tekenen geeft foutmelding

### ISSUE THREAD

**Issue by vnogzwarta** [OIV-NL-QGIS/OIV_project#391]
Als je een bouwlaag wilt toevoegen lukt dit niet als je deze zelf wilt tekenen. Het vreemde is dat als je eerst een heel nieuw object aanmaakt, een terrein tekent en daarna een bouwlaag wilt toevoegen door zelf te tekenen het dan wel lukt. Daarna kun je ook bij bestaande objecten weer een bouwlaag toevoegen door zelf te tekenen. Na afsluiten is het weer niet mogelijk en komt de foutmelding weer terug.
Onderstaande komt in beeld:
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/66950297/442a7340-98e5-4c47-8856-c54112130f74)

**Comment by ghost** [comment]
Mogelijk gerelateerd aan #387
