### ISSUE TITLE
Historie bijwerken verlaten bouwlaag

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#393]
1.	Als je bij verlaten van Terrein op de knop [Gereed] klikt komt het volgende scherm:
 
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/95032611/83472a52-af09-47af-93ab-ef9f0c0f1917)

Dit venster verschijnt alleen bij verlaten van Terrein, niet bij het verlaten van Bouwlaag. 
Dit venster ook bij verlaten Bouwlaag laten verschijnen (omdat je daarna de plug-in kunt sluiten zonder aan bijwerken historie gedacht te hebben).

**Comment by Oostjoost** [comment]
Er is geen relatie tussen historie en bouwlaag. Er wordt geen historie per bouwlaag bijgehouden. Alleen per i-tje.
