### ISSUE TITLE
Knoppen omdraaien

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#394]
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/95032611/39fbd49b-4a90-493b-8418-f2a32a2938c2)

Het is logischer als de knoppen [Object verwijderen] en [Terrein verwijderen] omgedraaid worden.
Zolang de verwijder functie (zowel terrein- als gebouw verwijderen) niet goed werkt is dat namelijk de volgorde van ‘afbreken’: eerst het Terrein (en de rest) en als laatste het Object (blauwe info-dot).

**Comment by Oostjoost** [comment]
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/23038880/4233e078-0bab-4fb4-8969-3c88cb6100dc)
