### ISSUE TITLE
Toevoegen bouwlaag

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#395]
Bij toevoegen van een Bouwlaag (knop Bouwlaag > Toevoegen > Bouwlaag > OK) verschijnt onderstaand scherm:
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/95032611/037d51f1-e017-4e18-935e-00304b9f877a)
 
Dat is inclusief tekenhulp: Lengte (m), Oppervlakte (m2) etc. (tussen grijs veld met ‘1’ en ‘Bouwlaag toevoegen’).

Klik je op knop [Bouwlaag zelf tekenen] dan komen bovenaan nog een keer dezelfde tekenhulpen erbij. Dat is raar en verdwijnt ook niet meer totdat je OIV helemaal afsluit.
 
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/95032611/5a475bae-cd60-4dae-a9a5-fdb6814be1ff)

**Comment by Oostjoost** [comment]
Is volgens mij in de laatste versie al verholpen? Want ik krijg dit in ieder geval niet. Ik krijg alleen de bovenste tekenhulp
