### ISSUE TITLE
Twee bouwlagen over elkaar

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#396]
Het is mogelijk om op een bouwlaag een zelfde, reeds aanwezige bouwlaag te kopiëren. Dat valt in zijn geheel niet op (heb dat op verschillende plekken in planvorming NHN gezien).
Twee mogelijkheden:
* Indien twee identieke aan dezelfde bag gekoppeld: Als je 1 van de 2 wil verwijderen wordt mogelijk de ‘achterste’ geselecteerd. Je zult niet zien dat die paars wordt omdat er 1 voor zit.
* Indien twee verschillende aan dezelfde bag gekoppeld: Als je er 1 wil verwijderen, krijg je niet de keuze welke (zit er nog andere planvorming aan gekoppeld?).

Is dit te voorkomen?

**Comment by Oostjoost** [comment]
Het is de code te voorkomen dat je het naar dezelfde bouwlaag kunt kopieren. Dat is de beste oplossing denk ik.
