### ISSUE TITLE
Meerdere bouwlagen

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#397]
Als je extra bouwlagen creëert, bijv. bouwlaag 2 t/m 3 en je kopieert die van bouwlaag 1, dan kun je dat prima opgeven, zie hieronder:
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/95032611/6002f1ae-015d-450c-8488-2d07acb88f8f)
 
Maar zodra je op knop [Selecteer en Kopieer] klikt krijg je geen respons / bevestiging dat het gebeurt / gelukt is.
Klik je op de knop [Terug] dan blijft de actieve bouwlaag (in dit geval) 2 (‘zie vak ‘De nu weergegeven bouwlaag is: 2’). Ook na sluiten van de OIV Plug-in blijft deze 2 zodat je geen planvorming meer ziet.
Alhoewel QGIS aangeeft dat de Actieve bouwlaag 1 is, wordt pas na opnieuw openen van de Plug-in de zichtbare bouwlaag weer gereset naar 1.

Maar ook, als je in QGIS de Actieve Bouwlaag op ‘2’ zet en dan OIV opstart wordt de Actieve Bouwlaag op ‘1’ terug gezet.
Ergo, binnen de plug-in kun je schakelen tussen bouwlagen. Maar dat wordt niet aan QQIS doorgegeven:
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/95032611/efe3bcdf-8592-4661-b0bd-6238a4cd9bdf)
 
Blijkbaar is er geen koppeling tussen beide. Dat is raar.

**Comment by Oostjoost** [comment]
Switchen in de werkbalk bij gebruik van de plugin wordt niet voor niets uitgezet. Dit is niet de bedoeling en zorgt voor ongewenst gedrag van de plugin. "Actieve bouwlaag" staat standaard op 1, en reageert nergens meer op na het starten van de plugin. Daarom is hij ook uitgegrijst. 

Bij het kopieren van een andere bouwlaag gaat hij terug naar 1 zodat je de juiste bouwlaag kunt selecteren. Je moet dan op de bouwlaag/bouwdeel klikken omdat de plugin niet weet of je bijvoorbeeld van bouwlaag 2, bouwdeel A of B wilt selecteren.

Mogelijk kan e.e.a. gewijzigd worden maar dit is al tijden de werkwijze om een bouwlaag te kopiëren. Bij "Terug" selecteert de plugin op dat moment geselecteerde bouwlaag.
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/23038880/a0022fb0-b992-4fe2-a6e4-6bf7b5b63198)

**Comment by Oostjoost** [comment]
Er wordt geen oplossing of antwoord gegeven
