### ISSUE TITLE
Heel veel vertraging tijdens het tekenen van iconen ook na opnieuw opstarten

### ISSUE THREAD

**Issue by Frankvrzw** [OIV-NL-QGIS/OIV_project#403]
Heel veel vertraging tijdens het tekenen van iconen ook na opnieuw opstarten. Hij doet wel wat er moet gebeuren maar het duurt gewoon erg lang. Zie video voor voorbeeld

**Hoe te reproduceren**
Beschrijf de stappen hoe de bug te reproduceren is:
1. '...'
2. '...'
3. 

**Stapelspoor**
Maak waar mogelijk een screenshot van het stapelspoor

**Wat wordt er verwacht**
Beschrijf kort en duidelijk welk gedrag er wordt verwacht van de applicatie

**Screenshots**
Indien van toepassing voeg screenshots of een filmpje toe.

**Op welk device kwam de issue naar voren**
 - Besturingssysteem en versie: 
 - QGis versie:

https://github.com/OIV-NL-QGIS/QGIS_project/assets/134381329/2062be9e-7a60-40bf-b9d9-8ffe431d911f

 - Database connectie of WFS connectie:
 - Welke versie van Postgres/PostGis:
 - Welke versie van GeoServer:

**Wilt u verder nog wat opmerken**

**Comment by Oostjoost** [comment]
Dat duurt inderdaad wel erg lang. Als ik een connectie maak met jullie database dan gaat dat veel sneller. Kan het zijn dat de verbinding bij jullie geknepen wordt op de Wifi?

**Comment by Frankvrzw** [comment]
we zitten wel op de andere kazerne, maar volgens mij is het lokaal geïnstalleerd en we werken gewoon via de kabel.
Het lijkt ook niet altijd bij iedereen te gebeuren maar random

**Comment by Oostjoost** [comment]
Ik weet haast zeker dat dit een netwerk probleem is. Dit had Fryslan ook. Daar zaten ze op een bepaald wifi netwerk waarbij die maar 20% van de bandbreedte gebruikte. Als er meerdere tekenaars tegelijk werken, zorg t dit al snel voor performance daling. Misschien even met Bob of ICT afstemmen?

**Comment by Frankvrzw** [comment]
Ga ik doen Thanks

**Comment by Joachim-Tempelaars** [comment]
Bob neemt het inter op

**Comment by OIV-NL-QGIS** [comment]
intern vrzw
