### ISSUE TITLE
Geen feauture melding bij tekenen iconen

### ISSUE THREAD

**Issue by Frankvrzw** [OIV-NL-QGIS/OIV_project#404]
Tijdens het tekenen van een deur icoon geeft het programma meerdere malen aan dat er geen feature geselecteerd is. Je kan wel doordrukken en de icoon wordt ook gewoon geplaatst. klopt dit wel?

https://github.com/OIV-NL-QGIS/QGIS_project/assets/134381329/7218e19f-018c-4217-adfe-01bab69017c6

**Comment by Oostjoost** [comment]
Ik vermoed dat er nog een "selectietool" of "verwijdertool" aan je muis hing. Kun je het reproduceren? Dan kan ik kijken of ik het kan afvangen.

**Comment by Frankvrzw** [comment]
Het gebeurt tot nu toe vaak bij gebouwen die in de Laag bag panden PDOK  dus niet de PDOK database. Het gebouw moet nog gebouwd worden.  kan het daar aan liggen?

**Comment by Frankvrzw** [comment]
heb hetzelfde probleem nu met meerdere collega's gehad alles vanuit opstarten dus er kan niet geselecteerd zijn

**Comment by Oostjoost** [comment]
Opgelost, hij zoekt naar lagen om aan te snappen, daarbij kijkt hij ook naar de BAG laag. Als deze er niet is dan geeft hij die melding. Ik heb hem nu "optioneel" gemaakt als snap laag
