### ISSUE TITLE
Werkvoorraad lijkt niet altijd te werken.

### ISSUE THREAD

**Issue by Frankvrzw** [OIV-NL-QGIS/OIV_project#405]
Als je probeert een ruimtelijk label weg te halen verdwijnen ze niet maar komen er rode kruizen bij te staan. Ze komenniet in de werkvoorraad van het terrein te staan. Deze blijft grijs? ziet foto

Een gerelateerd issue is dat als je twee ruimten samenvoegt dit ook niet in de werkvoorraad van een bouwlaag terecht komt.

**Wilt u verder nog wat opmerken**
![Werkvoorraad terrein werkt niet](https://github.com/OIV-NL-QGIS/QGIS_project/assets/134381329/e2a3aee6-14e9-4c69-b13a-4efefba5168a)

**Comment by Oostjoost** [comment]
Ik krijg dat alleen gereproduceerd als ik iets verwijder met de tool van QGIS zelf en krijg het niet voor elkaar als ik wat verwijder met de plugin. Via de verwijder tool van QGIS zelf is dat een bekend issue.... #200

**Comment by Frankvrzw** [comment]
We hebben wel hetzelfde probleem als we bijvoorbeeld ruimten samenvoegen. dit kan niet met de plugin en veroorzaakt hetzelfde probleem dat het soms wel en soms niet in de werkvoorraad komt.

**Comment by Frankvrzw** [comment]
![werkvoorraad 2](https://github.com/OIV-NL-QGIS/QGIS_project/assets/134381329/9b4659f0-862b-4e9c-8178-f89ecb33d4b1)
Ook als ik de werkvoorraad gewoon in een bouwlaag wil aanspreken zie ik ze niet terug en kan ik dus de iconen niet verwijderen

**Comment by Frankvrzw** [comment]
ditzelfde geld ook voor labels ze zijn niet selecteerbaar.
