### ISSUE TITLE
Minimale bouwlaag -1 in objectgegevens wordt niet opgeslagen

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#406]
Wanneer je in de objectgegevens de minimale bouwlaag veranderd in -1 / -2 / -3 / -4 dan wordt dit niet opgeslagen na "Opslaan en terug". Na weer openen staat deze weer gewoon op 1.

![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/95032611/5d5bd34d-7cf5-4ba8-aa64-c8ec5fa62607)

**Comment by Oostjoost** [comment]
Ik kan dit niet reproduceren. Bij mij slaat hij keurig de waarde op. Kun je eens in de database kijken of de kolomnamen goed staan en goed genoemd zijn:
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/23038880/58b94d41-8b08-4304-a75f-757a53b95743)

**Comment by CarloNannings** [comment]
Hoogste en laagste bouwlaag staat 2x in de database.
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/95032611/03e969db-b486-4da5-a6b9-d3987c56d608)
