### ISSUE TITLE
Sleutelkluis pictogram verdwijnt

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#407]
Wanneer je het pictogram brandweeringang of neveningang verwijderd, verwijderd het pictogram sleutelkluis ook.
Zie filmpje.

https://github.com/OIV-NL-QGIS/QGIS_project/assets/95032611/f396e1e8-d6f2-4c72-811b-35b5e1861b69

Het gebeurd zelfs dat alle sleutelkluizen van dit pand verwijderd worden. Bij 1 van de panden verdwenen 8 sleutelkluizen in één keer na verwijderen (neven)ingang.

**Comment by Oostjoost** [comment]
Dit is de correcte werking en is altijd al zo geweest. Een sleutelkluis zit relationeel gekoppeld aan een ingang. Als dit aangepast moet worden moeten we het datamodel ombouwen. Dit heeft best wat impact.
