### ISSUE TITLE
er verdwijnen random bouwlagen in qgis?

### ISSUE THREAD

**Issue by Frankvrzw** [OIV-NL-QGIS/OIV_project#409]
Bij meerdere collega's en op meerdere locaties bouwlagen. vaak als je wilt wisselen staat alleen de eerste bouwlaag erin terwijl er meerdere zijn. Na het opnieuw opstarten is het probleem vaak weer weg.
Hebben meerdere regio's hier last van?

**Comment by Oostjoost** [comment]
Zonder duidelijke beschrijving kan ik hier helaas niet zoveel mee, indien mogelijk laten weten hoe het te reproduceren is.

**Comment by IrenevanderZwan** [comment]
hier heeft de VRK nu geen last van.

**Comment by Oostjoost** [comment]
Andere regio's lijken hier geen last van te hebben. Meenemen in de test van 3.5.03
