### ISSUE TITLE
Aanpassingen in bluswaterproject

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#410]
Ik zou graag de volgende aanpassingen in het bluswaterproject willen doorvoeren:

• 

- [x] Bij brandkraaninspectie:

o Afgekeurd en ter reparatie --> aanpassen ‘t’ naar ‘true’ (2x in deze regel)
o Werkbaar en reparatie --> aanpassen ‘t’ naar ‘true’ (2x in deze regel)
o Toevoegen: (paars bolletje) reparatie gemeente uitgevoerd --> "conditie" = 'reparatie uitgevoerd'
o Toevoegen: (zwart bolletje) brandkraan vervallen --> "conditie" = 'vervallen'

• 

- [x] De volgende vinkjes standaard zetten bij opstarten project:

o Stavaza-per gemeente --> Uit
o Brandkraaninspectie --> Aan
o Waterleidingbedrijf --> Uit

- [x] Zichtbaar maken dat naar gemeente en/of PWN gemelde reparaties “over de datum zijn” om vinger aan de pols te houden over de voortgang.

- [x] Zoekfunctie om te zoeken op brandkraannummer zoals in Cogo.

- [x] Bij "Inspectie - object attributen" in brandkraan project staat bij "Conditie" de tekst inspecteren. Deze tekst graag weglaten. "Inspectie" staat al in het keuzemenu.

- [x] Foto uit Cogo app wordt niet zichtbaar bij “Brandkraaninspectie”.

- [x] Als in “QGIS Bluswater” een brandkraan van inspecteren naar werkbaar gezet wordt en vervolgens wordt deze doorgestuurd naar de gemeente, dan blijft de brandkraan donkerblauw in plaats van oranje. Het doormelden naar de gemeentelijke Cogo-app functioneert in beide gevallen niet.

- [x] De bovengrondse brandkraan ontbreekt bij de alternatieve bluswatericonen.

- [x] Tabellen bluswater vanuit de database ophalen bv enum_conditie

Doorgenomen en afgestemd met VRZW en besproken in het GitHub overleg. Beide zijn akkoord met de wijzigingen.

**Comment by Oostjoost** [comment]
Zichtbaar maken dat naar gemeente en/of PWN gemelde reparaties “over de datum zijn” om vinger aan de pols te houden over de voortgang.

Wat is "over de datum"? Binnen welke termijn dient het gerepareerd te zijn?

**Comment by CarloNannings** [comment]
Reparatie dient binnen 2 maanden gerealiseerd te zijn.

**Comment by Oostjoost** [comment]
o Toevoegen: (zwart bolletje) brandkraan vervallen --> "conditie" = 'vervallen'
Ik filter de brandkranen al op de waarde "Buiten werking" of "Uitgenomen" Dit heeft dus niet heel veel zin als je de brandkranenset regelmatig ververst.

**Comment by CarloNannings** [comment]
OBK's bestaan nog maar gaan op termijn vervallen.
Voor het overzicht graag het zwarte bolletje wel toevoegen of "Buiten werking" zichtbaar maken met een bolletje.

**Comment by Oostjoost** [comment]
> OBK's bestaan nog maar gaan op termijn vervallen. Voor het overzicht graag het zwarte bolletje wel toevoegen of "Buiten werking" zichtbaar maken met een bolletje.

In de PWN dataset zitten alleen de waarden:
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/23038880/83eedfe3-54d0-44c4-a54f-9e4f5dc8803d)
Dus "vervallen" bestaat niet

**Comment by Oostjoost** [comment]
Voor het doorzoeken van een laag zijn er meerdere mogelijkheden. Zoeken of selecteren via een expressie, maar ook via de plugin "Search Layers" Met onderstaande instellingen kun je gemakkelijk de laag Insectie doorzoeken.

Indien dit niet volstaat zal er een plugin apart moeten worden gemaakt voor Bluswater. En deze bestaat nu niet.

![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/23038880/832cd560-ca68-4902-bf01-93dacd87096a)

**Comment by Oostjoost** [comment]
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/23038880/a0e9b604-1011-4c47-b7d6-2f3e561dd531)
brandkraan -> status vervallen -> zwart
brandkraan -> reparatie uitgevoerd -> paars

**Comment by CarloNannings** [comment]
Top

**Comment by Oostjoost** [comment]
Als in “QGIS Bluswater” een brandkraan van inspecteren naar werkbaar gezet wordt en vervolgens wordt deze doorgestuurd naar de gemeente, dan blijft de brandkraan donkerblauw in plaats van oranje. Het doormelden naar de gemeentelijke Cogo-app functioneert in beide gevallen niet.

Rapport voor de gemeente vereist dat:
(rapport_inspectie_defect.plaatsaanduiding IS NOT NULL OR rapport_inspectie_defect.plaatsaanduiding_anders IS NOT NULL OR rapport_inspectie_defect.toegankelijkheid IS NOT NULL OR rapport_inspectie_defect.toegankelijkheid_anders IS NOT NULL)

Als deze niet zijn gevuld dan komt hij ook niet terug in de lijst voor de gemeente als het goed is. Bij mij verandert de status netjes naar oranje als ik hem op werkbaar zet, en naar oranje + geel als ik hem op "uitgezet" zet

**Comment by Oostjoost** [comment]
Foto uit Cogo app wordt niet zichtbaar bij “Brandkraaninspectie”.
Hier heb ik de URL nodig waar de foto is opgeslagen

**Comment by Oostjoost** [comment]
Zichtbaar maken dat naar gemeente en/of PWN gemelde reparaties “over de datum zijn” om vinger aan de pols te houden over de voortgang.
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/23038880/ca6a51b0-afb9-4088-8c36-45854cd5616a)

**Comment by CarloNannings** [comment]
Ziet er goed uit. Thx

**Comment by Oostjoost** [comment]
Foto uit Cogo app wordt niet zichtbaar bij “Brandkraaninspectie”.

Apart issue van gemaakt
