### ISSUE TITLE
Foutmelding bij toevoegen ruimte (3.5.2)

### ISSUE THREAD

**Issue by APostmaVRF** [OIV-NL-QGIS/OIV_project#420]
Bij het toevoegen van een ruimte (verkeersruimte, bijzondere_ruimte etc.) onderstaande foutmelding:

![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/134285699/fa98d91d-caa0-4557-aa4b-6ff393bb88b4)

**Comment by Oostjoost** [comment]
Onduidelijk hoe ik deze melding kan reproduceren. Als ik nu een ruimte teken gaat het goed. @APostmaVRF Zou je aan kunnen geven welke acties je precies uitvoert? Waaraan je snapt etc?

**Comment by Oostjoost** [comment]
Na overleg met Arjan blijkt de foutmelding niet meer voor te komen en reeds te zijn opgelost.
