### ISSUE TITLE
Huisnummers

### ISSUE THREAD

**Issue by DKraijer** [OIV-NL-QGIS/OIV_project#423]
De huisnummers missen op de kaart. Graag weer toevoegen

**Comment by DKraijer** [comment]
BAG-huisnummering zou de laag moeten zijn

**Comment by Oostjoost** [comment]
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/23038880/dfd1f6db-c16b-4fde-9574-ddc83d06f7d2)

**Comment by Oostjoost** [comment]
Ook toegevoegd aan Bluswater beheer

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/QGIS_project/commit/739840112a1c4ebaf21633271a27e4aac75f7772
resolves #423
