### ISSUE TITLE
Na afsluiten van de plugin terug naar bouwlaag 1

### ISSUE THREAD

**Issue by vnogzwarta** [OIV-NL-QGIS/OIV_project#427]
Als je in bijvoorbeeld bouwlaag 2 tekent en dan de plugin afsluit blijft QGIS op bouwlaag 2 staan. Bovenin de werkbalk geeft QGIS bouwlaag 1 aan omdat daar geen keuze in is gemaakt. Vervolgens moet je dan even tussen bouwlagen wisselen om bouwlaag 1 weer zichtbaar te krijgen. verzoek om na afsluiten plugin standaard naar bouwlaag 1 te gaan.

**Comment by Oostjoost** [comment]
Ik denk dat dit maximaal 2 uur kost om te ontwikkelen. Dan wordt op basis van de selectie bovenin die bouwlaag geselecteerd. Bij openen van de plugin gaat alles naar bouwlaag 1. Is dat gewenst?

**Comment by Oostjoost** [comment]
[47089926a77071e731e1ba8aea9fd6550751c333](https://github.com/OIV-NL-QGIS/QGIS_project/commit/47089926a77071e731e1ba8aea9fd6550751c333)
resolves #427
