### ISSUE TITLE
Bouwlaag toevoegen via BAG (3.5.2)

### ISSUE THREAD

**Issue by APostmaVRF** [OIV-NL-QGIS/OIV_project#429]
Bij het toevoegen van een bouwlaag via BAG de volgende Phython melding:

![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/134285699/84e815d8-d55c-4868-bb02-62fd4dbee4a0)

**Comment by Oostjoost** [comment]
duplicates #417 welke al is opgelost

**Comment by APostmaVRF** [comment]
@Oostjoost is nog niet helemaal opgelost. Krijg nog steeds een Phytonmelding.

![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/134285699/e87598dc-cd93-49bd-8ee0-ce8b4191eca7)
