### ISSUE TITLE
Aanrijdroute wijzigen

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#435]
Met de laatste OIV update is de aanrijdroute lijn (groen met pijlen) gewijzigd van:
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/95032611/a331d658-f3d2-4983-931f-a11a4a744a11)

In:
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/95032611/0f0566eb-f8c9-4b06-abf6-bcaeb6d47b7a)
 

Graag het aantal pijlen op de lijn terug laten brengen tot wat het was.

**Comment by Martijnjansenvrk** [comment]
Zoals vorige week afgesproken in het overleg het onderstaande zo volledig mogelijk invullen:

**Beschrijf de bug - kort en duidelijk**
 
**Hoe te reproduceren**
Beschrijf de stappen hoe de bug te reproduceren is:
1. '...'
2. '...'
3.
 
**Stapelspoor**
Maak waar mogelijk een screenshot van het stapelspoor
 
**Wat wordt er verwacht**
Beschrijf kort en duidelijk welk gedrag er wordt verwacht van de applicatie
 
**Screenshots**
Indien van toepassing voeg screenshots of een filmpje toe.
 
**Op welk device kwam de issue naar voren**
- Besturingssysteem en versie: 
- QGis versie:
- Database connectie of WFS connectie:
- Welke versie van Postgres/PostGis:
- Welke versie van GeoServer:
 
**Wilt u verder nog wat opmerken**

**Comment by CarloNannings** [comment]
Hoe duidelijk wil je het hebben!

**Comment by Oostjoost** [comment]
Wat mij betreft een ongegeldige melding/bug. Zie onderstaande, de "driehoekjes" worden alleen getekend op de punten van de lijndelen. Dat zou betekenen dat de bovestaande lijn uit heel veel verschillende lijndelen bestaat. Er is niets aan de styling veranderd.
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/23038880/a8ca4431-55b1-496e-b89a-b4da0e49cecf)

**Comment by Oostjoost** [comment]
Hebben andere regio's hier ook last van? @CarloNannings Is het alleen bij dit object of overal?

**Comment by CarloNannings** [comment]
Dit gebeurd op meerdere plekken. De aanrijdroute is **niet** veranderd tov eerdere plugin versies.

**Comment by Martijnjansenvrk** [comment]
Vandaag getest met de nieuwe plugin 3.5.03 icm qgis 3.22, en wij hebben dit zelfde probleem. 
Lijkt mis te gaan in de styling zelf en niet met hoe de lijn is getekend. Zie ook het onderstaande screenshot: 
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/67631279/f0ddfbe6-a153-437c-b023-f14c48290d97)

**Comment by DKraijer** [comment]
Ik heb gekeken en zie dat als je het aanpast naar onderstaande afbeelding de weergave weer "juist" is.
![Aanrijdroute](https://github.com/OIV-NL-QGIS/QGIS_project/assets/94529610/78adef02-1257-418a-b5db-d1d7877cdceb)

**Comment by Oostjoost** [comment]
Ik heb gister het project van internet af gedownload en daar staat de instelling binnen deze stijl op

- op elk punt
- op laatste hoekpunt
- op eerste punt

Nu bekeek ik de screenshot van @DKraijer en zag daar radiobuttons ipv vinkvakjes. Wat inhoud dat er maar één optie geselecteerd kan worden. Wat blijkt..... er zit een verschil tussen QGis 3.22 en QGis 3.28

Hierdoor weet QGis 3.22 niet wat hij moet selecteren en selecteert default de bovenste, "met intervallen"

![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/23038880/a1e55ce4-29be-49ff-9f08-8a069e1c048d)
