### ISSUE TITLE
OIV Print probleem

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#436]
Objecten uit QGIS kunnen niet (meer) uitgeprint worden.
Er zitten 3 I-tjes aan dit object, maar dat was nooit een probleem.
QGIS geeft geen foutmelding. Er is geen output.

![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/95032611/b7301ea2-8e25-4ac9-83a6-041b8c263343)

**Comment by Martijnjansenvrk** [comment]
Zoals vorige week afgesproken in het overleg het onderstaande zo volledig mogelijk invullen:

**Beschrijf de bug - kort en duidelijk**
 
**Hoe te reproduceren**
Beschrijf de stappen hoe de bug te reproduceren is:
1. '...'
2. '...'
3.
 
**Stapelspoor**
Maak waar mogelijk een screenshot van het stapelspoor
 
**Wat wordt er verwacht**
Beschrijf kort en duidelijk welk gedrag er wordt verwacht van de applicatie
 
**Screenshots**
Indien van toepassing voeg screenshots of een filmpje toe.
 
**Op welk device kwam de issue naar voren**
- Besturingssysteem en versie: 
- QGis versie:
- Database connectie of WFS connectie:
- Welke versie van Postgres/PostGis:
- Welke versie van GeoServer:
 
**Wilt u verder nog wat opmerken**

**Comment by CarloNannings** [comment]
Ook hier kan ik het niet duidelijker omschrijven!
Er is geen stapelspoor, geen foutmelding of wat dan ook.
De functie doet helemaal niets.

**Comment by Oostjoost** [comment]
Wat mij betreft een ongegeldige melding/bug. Zie onderstaande, de "driehoekjes" worden alleen getekend op de punten van de lijndelen. Dat zou betekenen dat de bovestaande lijn uit heel veel verschillende lijndelen bestaat. Er is niets aan de styling veranderd.
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/23038880/a8ca4431-55b1-496e-b89a-b4da0e49cecf)

**Comment by Oostjoost** [comment]
Oeps.... haha. Is opmerking bij #435

**Comment by Oostjoost** [comment]
Is dit probleem alleen bij dit object? Of ook bij "enkele" objecten?

**Comment by CarloNannings** [comment]
Probleem is na vorig overleg (28-11-2024) helder en besproken met Joost. 
Per I-tje is een object terrein nodig. Dit issue kan vervallen.
