### ISSUE TITLE
Foutmelding bij verwijderen symbool (3.5.03)

### ISSUE THREAD

**Issue by APostmaVRF** [OIV-NL-QGIS/OIV_project#437]
Bij het verwijderen van een symbool onderstaande Phyton melding:

![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/134285699/0941cd11-5746-4eaa-82d0-b7e8a1c44e53)

**Comment by Oostjoost** [comment]
Is als het goed is opgelost met de nieuwe scripts in de database. @APostmaVRF @Paulienv78
