### ISSUE TITLE
Kopiëren bouwlaag neemt de symbolen niet mee 3.5.03 

### ISSUE THREAD

**Issue by APostmaVRF** [OIV-NL-QGIS/OIV_project#441]
Bij het kopiëren van een bouwlaag worden de aangevinkte elementen niet mee gekopieerd, alleen de bouwlaag zelf.

![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/134285699/c44facdc-a02a-44a2-bf57-b55b9a73062c)

**Comment by Martijnjansenvrk** [comment]
Check je instellingen bij het kopiëren eens goed. Als je bouwlaag 1 probeert te kopiëren terwijl je ook bouwlaag 1 probeert aan te maken gaat het natuurlijk niet goed.

**Comment by Oostjoost** [comment]
Als ik het screenshot bekijk dan is de opmerking van Martijn terecht. De plugin houdt er rekening mee dat je niet over je al geselecteerde bouwlaag heen kunt kopiëren. Dit houdt in dat er nu niets gebeurd. Vermoedelijk was de bouwlaag zelf al aangemaakt.
