### ISSUE TITLE
 aanmaken bouwlaag

### ISSUE THREAD

**Issue by vnogzwarta** [OIV-NL-QGIS/OIV_project#442]
**Beschrijf de bug - kort en duidelijk**

**Hoe te reproduceren**
Beschrijf de stappen hoe de bug te reproduceren is:
1. 'Bij toevoegen bouwlaag krijg je een foutmelding na op het BAG pand te hebben geklikt, of als je een bouwlaag van een andere bouwlaag wilt overnemen'
2. 'Er komt wel een melding in beeld dat de bouwlagen succesvol zijn aangemaakt maar deze zijn niet zichtbaar, er komt geen geel vlak.'
3. 

**Stapelspoor**
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/66950297/9d82b035-3049-4cc5-8e44-df4a3adbf22b)

foutmelding:Laag Bouwlagen: PostGIS fout bij het toevoegen van objecten:ERROR: null value in column "id" ....etc.
![Foutmelding aanmaken bouwlaag](https://github.com/OIV-NL-QGIS/QGIS_project/assets/66950297/1b0ee1a2-38e5-4b02-a3f8-472e0f24bdd8)

**Wat wordt er verwacht**
Het daadwerkelijk aanmaken van een bouwlaag

**Screenshots**
Indien van toepassing voeg screenshots of een filmpje toe.

**Op welk device kwam de issue naar voren**
 - Besturingssysteem en versie: 3.5.03
 - QGis versie: 3.28.9
 - Database connectie of WFS connectie: 3.5.03
 - Welke versie van Postgres/PostGis: 10
 - Welke versie van GeoServer: n.v.t.

**Wilt u verder nog wat opmerken**

**Comment by Martijnjansenvrk** [comment]
Beste August, 

Check de rules onder de insert bij de view bouwlaag_bouwlagen eens, volgens mij ontbreken die namelijk bij jou.

**Comment by vnogzwarta** [comment]
Lijkt opgelost. Er staat een beschrijving over de update en daaronder de scripts die er zijn. Script 3 en 4 staan niet in de beschrijving.
![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/66950297/c22a9c15-ec71-4db5-9380-3500f42afd95)
