### ISSUE TITLE
Labels bij inrijpunten op de kop

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/OIV_project#443]
De labels welke bij de inrijpunten geplaatst worden staan op de kop

![labels inrijpunt](https://github.com/OIV-NL-QGIS/QGIS_project/assets/64782528/423bd4a8-d8e8-41da-bf12-1db77dac10fa)

**Comment by Oostjoost** [comment]
Alle labels overal staan op de kop en draaien mee met het symbool. Zet maar eens een label onder een ander symbool. Het symbool zelf staat ook op de kop
