### ISSUE TITLE
Opslag stoffen aanmaken/verwijderen 

### ISSUE THREAD

**Issue by vnogzwarta** [OIV-NL-QGIS/OIV_project#445]
Een aangemaakte stof kan niet meer verwijderd worden (bijv. omdat deze is komen te vervallen)

**Hoe te reproduceren**
Beschrijf de stappen hoe de bug te reproduceren is:
1. Oranje bordje wordt vanuit de plugin geplaatst
2. Doormiddel van de info knop voegen we 1 of meerdere stoffen toe
3. Als er dan een stof verwijderd moet worden, gaan we weer naar de opgeslagen stof en activeren deze en drukken op rode prullenbakje alleen dan gebeurt er niets

**Stapelspoor**
n.v.t

**Wat wordt er verwacht**
De geselecteerde stof moet verwijderd worden

**Screenshots**

![Aanmaken en verwijderen stoffen 3 5 03](https://github.com/OIV-NL-QGIS/QGIS_project/assets/66950297/56590bdc-065b-4c89-9195-14a67b170797)
 

**Op welk device kwam de issue naar voren**
 - Besturingssysteem en versie: 3.5.03
 - QGis versie: 3.28
 - Database connectie of WFS connectie:
 - Welke versie van Postgres/PostGis: 10
 - Welke versie van GeoServer:

**Wilt u verder nog wat opmerken**

**Comment by Oostjoost** [comment]
Filtering op de gevaarlijke stoffen moet nog worden gezet op basis van self_deleted

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/QGIS_project/commit/554f202a515094fb66a0662cdf9c0a14b63bc78c
resolves #445
