### ISSUE TITLE
aangemaakte schadecirkel wordt niet getoond

### ISSUE THREAD

**Issue by vnogzwarta** [OIV-NL-QGIS/OIV_project#446]
gekoppelde schadecirkel aan opslag stof wordt niet getoond.

**Hoe te reproduceren**
Beschrijf de stappen hoe de bug te reproduceren is:
1. Vanuit de plugin plaatsen we een opslag stof d.m.v. oranje bordje
2. We voegen hier een stof aan toe
3. Aan deze toegevoegde stof koppelen we een schadecirkel
4. Schadecirkel wordt ook aangemaakt maar niet getoond
5. Schadecirkel is ook weer gewoon te verwijderen door deze te selecteren en het rode prullenbakje aan te klikken.

**Stapelspoor**
n.v.t.

**Wat wordt er verwacht**
De gekoppelde schadecirkel moet getoond worden

**Screenshots**
![Aangemaakte schadecirkel niet zichtbaar](https://github.com/OIV-NL-QGIS/QGIS_project/assets/66950297/9323e427-f2ab-4ba4-82e9-41e6b03a3748)

**Op welk device kwam de issue naar voren**
 - Besturingssysteem en versie: 3.5.03
 - QGis versie:3.28
 - Database connectie of WFS connectie:
 - Welke versie van Postgres/PostGis:10
 - Welke versie van GeoServer:

**Wilt u verder nog wat opmerken**

**Comment by Oostjoost** [comment]
@vnogzwarta staat de kaartlaag "schadecrikel (alleen lezen)" wel aan?

**Comment by Oostjoost** [comment]
@vnogzwarta - keurig beschreven!!

**Comment by vnogzwarta** [comment]
kaartlaag Schade cirkel (alleen lezen) staat aan

**Comment by Oostjoost** [comment]
ook hier mist nog wel de filtering op self_deleted, die voeg ik ook hier toe. Ga nu even testen of ik er ook geen op de kaart zien. Heb je wel even uit en of ingezoomd na het tekenen? Het kaartbeeld moet wel even verversen.

**Comment by vnogzwarta** [comment]
kaartbeeld is in en uitgezoomd, plugin is opnieuw opgestart etc.

**Comment by Oostjoost** [comment]
- Bij schadecirkels mist er nog een stukje database migratie script:
- En zowel gevaarlijke stof als schade_cirkel werden niet gefilterd in QGIS zelf op self_deleted

Er komt nog één migratiescript voor de database naar 3.6.0, daar is het in opgenomen. En de filtering is toegepast in het QGIS project, deze wordt ook in 3.6.0 gereleased.


https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.5.03-3.6.00.sql
