### ISSUE TITLE
Management informatie ontbreekt

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#449]
De informatie uit de management informatielaag wordt niet getoond.

![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/95032611/52466cf2-08b8-4bb0-9fcc-d65cbeb738e6)

**Comment by vnogzwarta** [comment]
Als je de laag "Status van updaten" opent staan de lagen dan wel aan?

![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/66950297/054918cf-9a16-4245-bfdd-f491501761cc)

**Comment by CarloNannings** [comment]
Maakt niet uit welke laag ik aanzet. Management informatielaag wordt niet getoond.

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.5.03-3.5.04.sql
resolves #449
