### ISSUE TITLE
Kolom "datum deleted" omzetten in "self deleted".

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#450]
In de tabel alternatieve in bluswater ontbreekt de kolom "self deleted". "datum deleted" moet hier nog omgezet worden.
Onderstaande foutmelding ontstaat als je bij repressief object tabblad Bluswater iets weg wil gooien. 

![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/95032611/4d6cd8c3-1fc0-4e8c-a806-460e44510425)

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.5.03-3.6.0.sql
na het draaien van dit script en de nieuwe release gaat alles met alternatief bluswater ook goed.
