### ISSUE TITLE
Stoffen record wordt niet opgeslagen

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#451]
Als er een wijziging aangebracht wordt in een Stoffen record, wordt dat niet opgeslagen.
Na klikken op [floppy] en [Opslaan en terug] en daarna de stoffen record weer openen is er niets gewijzigd.

![image](https://github.com/OIV-NL-QGIS/QGIS_project/assets/95032611/c24eb46e-c1ee-47d9-b4b3-085f8cb77f77)

**Comment by Oostjoost** [comment]
Sowieso hoef je bij ee nieuwe stof niet te klikken op opslaan. Er komt ene pop-up formulier welke automatsich opslaat. Het enige wat ik zie gebeuren is dat het formulier niet ververst. als je dan even op "Opslag stoffen" klikt en weer terug naar "Stoffen" staat hij er gewoon bij.

Zouden jullie het kunnen verduidelijken aan de hand van een filmpje of reproductie stappen?

**Comment by CarloNannings** [comment]
Joost,

We doorlopen de volgend stappen:

  *   Via bouwlaag - tekenen - formulier van object openen (I-tje) - en dan pictogram gevaarlijke stof (oranje bord)
  *   In het tabblad "Stoffen" potloodje aanklikken om te wijzigen
  *   De "Omschrijving" wijzigen van bv butaan in propaan
  *   Daarna de bewerking opslaan en het potloodje uitvinken
  *   "Opslaan en terug"
  *   Wanneer je nu weer teruggaat om de info te controleren is de wijziging niet opgeslagen.

Duidelijk? Anders even meekijken via teams.

Groet,
Carlo

**Comment by Oostjoost** [comment]
Na analyse blijkt dat QGIS niet kan omgaan met een PostGIS tabel welke een op multi kolom primary key heeft. Gevaarlijke stof heeft deze key nodig omdat cascade delete mogelijk moet zijn met schade cirkels. Om dit op te lossen zal er in de database een view moeten worden aangemaakt die editing afhandelt net zoals de geometrie lagen. Dit wordt meegenomen in de komende release van 3.6.1
