### ISSUE TITLE
Filterfunctie voor het delen van data

### ISSUE THREAD

**Issue by 31081970** [OIV-NL-QGIS/OIV_project#452]
Graag willen wij een filter functie voor het (landelijk) delen van data. Is het mogelijk om middels een vinkje (dat standaard aan staat) de keuze te krijgen om data wel of niet te delen.

**Comment by OIV-NL-QGIS** [comment]
Het vinkje aan of standaard uit moet instelbaar zijn in de beheer DB.
Joost gaat uren inschatting maken

**Comment by Oostjoost** [comment]
Inschatting - 2u

- [x] Aanpassen invulbaar op object info blad
- [x] datamodel aanpassen
- [x] Alle view_ views aanpassen
- [x] Objectegegevens view aanpassen

Boolean waarde.... delen met externen of alleen intern. Vinkveld bij Objectinfo

Regio stelt in geoserver de CQL-filter in en maakt "interne" en "externe" DBK lagen.

**Comment by vnogzwarta** [comment]
Default alles delen en dan naar behoefte vinkje uitzetten

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.6.0-3.6.1-1.sql
