### ISSUE TITLE
Testen Q-gis 334  met plugin 3.6.0

### ISSUE THREAD

**Issue by 31081970** [OIV-NL-QGIS/OIV_project#453]

**Comment by vnogzwarta** [comment]
Binnen de VNOG hebben we QGIS 3.34 en OIV 3.6.0 getest en zijn geen bijzonderheden tegengekomen. 
1 punt van aandacht: Na het plaatsen van het symbool Opslag stoffen (oranje bordje) en vervolgens hier een stof aan gekoppeld te hebben is de gekoppelde stof niet aan te passen of te verwijderen. Dit is al aan Joost voorgelegd of dit zo bedoeld is of dat hiervan nog een apart issue aangemaakt moet worden.

**Comment by markbrw08** [comment]
Bij het opstarten van Qgis blijft Qgis een pop venster met project opslaag tonen. Dit lijkt ontstaan te zijn na installatie van de plugin 3.6.0 op Qgis 334.


![Qgis_OIV](https://github.com/OIV-NL-QGIS/QGIS_project/assets/173274568/0808f6d5-47f5-4173-89bd-a754452c1ca3)

**Comment by vnogzwarta** [comment]
Komt in de vorige versies van QGIS ook voor. 
Als je opstart en afsluit krijg je deze melding

**Comment by Oostjoost** [comment]
Bij het openen van QGIS is dit altijd het geval, omdat hij standaard met een kaal project opent. Dit heeft niets met OIV te maken.
