### ISSUE TITLE
Problemen bij printen van een enkele bouwlaag

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#456]
Als je een enkele bouwlaag wil printen (dus niet van het hele repressieve object) dan verwacht je dat de bouwlaag geprint wordt die op dat moment actief is (in OIV). Dat blijkt niet het geval. 
ALS het al lukt wordt eerst de bovenste bouwlaag geprint dan die daaronder enzovoort. Maar soms lukt het niet om alle bouwlagen geprint te krijgen. QGIS blijft dan in een soort van ‘ik ben bezig’ modus. Maar dat kan ie uren volhouden. Dat kan een netwerk of OIV-versie issue zijn maar misschien ook een bug.

Printen duurt sowieso lang, dus is het mogelijk om alleen de laag te printen die in OIV geselecteerd is of een keuzemogelijkheid/vraag welke lagen je geprint wil hebben.

**Comment by 31081970** [comment]
#481
