### ISSUE TITLE
Graag plugin verwijderen uit Qgis Plugin Store

### ISSUE THREAD

**Issue by Martijnjansenvrk** [OIV-NL-QGIS/OIV_project#457]
Door dat er harde regels staan in de tabellen die worden getoond in het Qgis project ontstaan er problemen wanneer je alleen de plugin  (vanuit Qgis) update. 

Voorbeeld; De kaartlaag alternatieve bluswater heeft in het project bestand de regen te filteren op een waarde uit de database "datum_deleted = NULL", in de database is dit hernoemd naar "self_deleted" waardoor de kaartlaag niet meer wordt getoond en dus foutmeldingen blijft geven als je dus niet het project bestand vernieuwd. Dus los updaten van alleen de plugin heeft dus geen zin. 

Kan dit veranderd worden, of te wel de plugin niet meer aan te bieden in de Qgis Plugin Store omdat dit momenteel niet de werkzaam is en dus ook problemen geeft wanneer je de database hebt ge-update.

**Comment by Oostjoost** [comment]
Ik heb hem verwijderd uit de online repository
