### ISSUE TITLE
zwembad_binnen werkt niet in bouwlagen

### ISSUE THREAD

**Issue by APostmaVRF** [OIV-NL-QGIS/OIV_project#459]
In Bouwlagen kan de ruimte zwembad_binnen niet gebruikt worden.
Onderstaand de foutmelding:

![image](https://github.com/user-attachments/assets/92c7237c-3573-4e45-b7d8-f8c50e056f49)

**Comment by Oostjoost** [comment]
ruimten_type miste in de database zoals de melding aangeeft. Deze toegevoegd in Fryslan en dit heeft het issue verholpen
