### ISSUE TITLE
Pythonfout bij import dxf-file 

### ISSUE THREAD

**Issue by Martijnjansenvrk** [OIV-NL-QGIS/OIV_project#460]
**Beschrijf de bug - kort en duidelijk**
Bij het object Spaarne Gasthuis Noord krijg ik bij het importeren van tekening (.dxf) krijg ik een Python Error. Het importeren van de tekening gaat op dezelfde manier zoals ik dat eerder deed.  
Het maken van de mapping gaat nog goed maar bij het valideren van de import gaat het fout.  
Betreft de 2e bouwlaag, wanneer ik andere bouwlagen aanmaak, krijg ik dezelfde foutmelding.  

**Hoe te reproduceren**
Beschrijf de stappen hoe de bug te reproduceren is:
1. De Plugin openen. 
2. Tab ‘bouwlaag’openen en op het betreffende object klikken.  
3. Knop ‘Toevoegen’ 
4. klik op importeer tekening 
5. kies het betreffende bestand 
6. loop de aangegeven stappen door tot en met ‘maak mapping’ 
7. klik op ‘Valideer import’  (Hierna komt de foutmelding)

**Stapelspoor**
Maak waar mogelijk een screenshot van het stapelspoor
![image](https://github.com/user-attachments/assets/4b8fb9b2-7c07-4d0f-b22a-6d17b443e97b)

**Wat wordt er verwacht**
Beschrijf kort en duidelijk welk gedrag er wordt verwacht van de applicatie
Ik verwacht dat het lijnenstel uit de .dxf file worden overgenomen in de bouwlaag in QGIS. 

**Screenshots**
Indien van toepassing voeg screenshots of een filmpje toe.

**Op welk device kwam de issue naar voren**
 - Besturingssysteem en versie: Windows 10 / 11
 - QGis versie: 3.34.6 LTR
 - Database connectie of WFS connectie: Database
 - Welke versie van Postgres/PostGis: 
 - Welke versie van GeoServer:

**Wilt u verder nog wat opmerken**

**Comment by Oostjoost** [comment]
Het lukt mij niet om dit issue te reproduceren in QGIS versie 3.28. Ik zal het eens proberen in 3.34.
Is het misschien een optie om de progressbar er uit te slopen? Ik vind het zelf een beetje een overbodige functie.

**Comment by Martijnjansenvrk** [comment]
Als dat het probleem oplost en dus ook in de toekomst geen problemen meer kan geven. Dan zou ik hem er gewoon uithalen.

**Comment by Oostjoost** [comment]
Dan doe ik dat, het heeft geen enkele meerwaarde. Het idee was leuk, maar eigenlijk die je hem nooit omdat alles zo snel is.
