### ISSUE TITLE
Verschillende problemen rondom printfunctie tbv overleg

### ISSUE THREAD

**Issue by JeliHaagsma-VRF** [OIV-NL-QGIS/OIV_project#473]
**Beschrijf de bug - kort en duidelijk**

Verschillende problemen rondom printfunctie

**Hoe te reproduceren**
Beschrijf de stappen hoe de bug te reproduceren is:
1. Printen via bouwlaag loopt QGIS vast. Wanneer er geprint wordt via terrein is er geen probleem. 
2. Voor enkele objecten (Jacobs Douwe Egberts in Joure en Lankhorst in Sneek) ervaren wij dat er helemaal niks wordt geprint. Ook niet via "terrein". 
3. Snelheid van het printen is traag voornamelijk grote objecten maar ook kleinere objecten laten lang op zich wachten. 

**Stapelspoor**
Er is geen stapelspoor. Er gebeurd 'niks' of QGIS crashed/loopt vast. 

**Wat wordt er verwacht**
Dat bouwlagen geprint kunnen worden in zijn volledigheid, dus niet half. 
Dat alle objecten geprint kunnen worden. 
Dat de wachttijd acceptabel is. 

**Screenshots**
Indien van toepassing voeg screenshots of een filmpje toe.

**Op welk device kwam de issue naar voren**
 -QGIS OIV: v3.6.0 

**Wilt u verder nog wat opmerken**
Dit is tbv het aparte overleg, om alle issues vanuit VRF nog even op een rijtje te hebben. Als dit overbodig is of niet de code of conduct mag het verwijderd worden.

**Comment by JeliHaagsma-VRF** [comment]
Aanvulling: De doelgroep waarvoor de printfunctie bij de VRF wordt gebruikt is om te delen met gemeenten.

**Comment by Oostjoost** [comment]
@JeliHaagsma-VRF , jij zou nog even kijken of punt 2 nog speelt en of die al is verwerkt in de andere issues. Zo ja, wil je die dan even verwerken in een nieuw issue en deze sluiten aangezien 1 en 3 al in andere issues zijn opgenomen.

**Comment by JeliHaagsma-VRF** [comment]
Punt 2 speelt niet meer bij ons. De andere punten zijn verwerkt in andere issues, dus ik sluit deze.
