### ISSUE TITLE
Tekortkomingen in de printfunctie

### ISSUE THREAD

**Issue by CarloNannings** [OIV-NL-QGIS/OIV_project#475]
Gebruikte software:
QGIS: 3.28.15
OIV: 3.6.0

Opmerkingen:
A.	Er wordt NIET opgemerkt dat er al een print gegenereerd is.
Heb je in een map al een print (pdf) staan (maakt niet uit, Repressief Object of Bouwlaag) en je geeft  weer een print opdracht van hetzelfde object, bijvoorbeeld na een wijziging in tekenwerk, dan komt er geen melding dat de pdf-file al bestaat en/of in gebruik is (pdf-reader). De print wordt wel gegenereerd (= tijdrovend) maar uiteindelijk niet weggeschreven. Er komt wel een melding dat het printen gereed is.
Bovenstaande is op te lossen door:
o	Versiebeheer. Bijvoorbeeld door datum-tijd aan de filenaam toe te voegen.
o	De gebruiker zelf een filenaam laten invullen. Indien de file bestaat, venster tonen met [file overschrijven ja/nee].

B.	In de Bouwlaag print wordt NIET de bijbehorende Objectnaam opgenomen.
Voorkeur: naam opnemen in format: {Object naam}, Bouwlaag: {x}.

C.	Heeft een pand meerdere Bouwlagen, dan gaat het printen NIET goed.
Geprint wordt de bovenste Bouwlaag, de overige lagen niet. Sowieso is het ongewenst dat per printopdracht telkens alle bouwlagen geprint worden. Dat vergt (heel) veel tijd.
Voorstel: vragen of alle lagen, de actuele laag, of een selectie geprint moet worden.
 (zie Acrobat Reader. Voor ‘pagina’s’ lees ‘lagen’)

D.	In de Object print wordt standaard de Object terrein laag weergegeven. Dit is niet altijd gewenst.
Voorkeur: zichtbaarheid instelling van Object terrein laag overnemen voor wel/niet afdrukken van deze laag.

E.	Je kunt NIET zelf de achtergrondkaart bepalen. Voor een Object print wordt de Openstreetmap gebruikt en voor Bouwlaag de Openbasiskaart.
Voorkeur: de geselecteerde Achtergrondkaart laag overnemen.

F.	Je kunt NIET zelf het afdrukbereik voor een print bepalen. Bij (zeer) grote objecten wordt de informatie op de print nu nauwelijks of niet leesbaar. Het afdrukbereik van een Repressief object is in te stellen door de contouren van het Object terrein (tijdelijk) aan te passen (die bepaald het afdrukbereik plus ..%). Bij een afdruk van een Bouwlaag is dat niet mogelijk.
Voorkeur: afdrukbereik met een polygoon selecteren.

G.	Bluswatervoorzieningen worden nu NIET geprint.
Voorkeur: zichtbaarheid instelling van Bluswater laag overnemen voor wel/niet afdrukken van de laag Alternatief bluswater en/of Brandkranen.

H.	Inhoud van het tweede- (Bouwlaag en Repressie object) en derde blad (alleen Repressie object) van de print is discutabel. Voor wie is een afdruk bestemd en wat moet er wel/niet in de afdruk opgenomen worden?
- opgave van Stoffen die zich in het pand bevinden wordt niet afgedrukt.
- moeten Historie gegevens wel afgedrukt worden?
- opnemen van een renvooi: opsomming van gebruikte pictogrammen

**Comment by 31081970** [comment]
@CarloNannings Deze issue's zijn opgeknipt in nieuwe issue's. graag even controleren met Wiebe of deze compleet zijn

**Comment by CarloNannings** [comment]
Alle issues zijn meegenomen en opgesplitst in afzonderlijke issues.
Dit issue mag gesloten worden.
