### ISSUE TITLE
Filenaam

### ISSUE THREAD

**Issue by 31081970** [OIV-NL-QGIS/OIV_project#477]
In de Bouwlaag print wordt NIET de bijbehorende Objectnaam opgenomen. 
Voorkeur: naam opnemen in format: {Object naam}, Bouwlaag: {x}.

**Comment by Oostjoost** [comment]
Een bouwlaag/pand kan onderdeel zijn van meerdere repressieve objecten. Graag specificeren hoe er moet worden bepaald welke naam dan moet worden gekozen om op te nemen in de bestandsnaam

**Comment by 31081970** [comment]
In collectief overleg besloten dat deze mag komen te vervallen.
