### ISSUE TITLE
Achtergrondkaart 

### ISSUE THREAD

**Issue by 31081970** [OIV-NL-QGIS/OIV_project#478]
Je kunt NIET zelf de achtergrondkaart bepalen. 
Voor een Object print wordt de Openstreetmap gebruikt en voor Bouwlaag de Openbasiskaart. 

Voorkeur: de geselecteerde Achtergrondkaart laag overnemen.

**Comment by Oostjoost** [comment]
Vrijgeven van de te printen kaartlagen ipv vooraf bepaald:
Inschatting 1 uur

**Comment by Oostjoost** [comment]
Dupliceert #480, ik sluit dit issue
