### ISSUE TITLE
Hekwerk

### ISSUE THREAD

**Issue by 31081970** [OIV-NL-QGIS/OIV_project#485]
Graag de lijn voor “hekwerk” zwart aangeven in de print. Grijs is nauwelijks te zien.

**Comment by Oostjoost** [comment]
Dan moet de stijl van een hekwerk aangepast worden naar zwart. Dit is niet heel veel werk.
Inschatting: 1u

**Comment by Oostjoost** [comment]
Dit is al opgelost volgens mij toen het hekwerk is aangepast naar een lijn met kruisjes ipv de zigzag driehoekjes.
![image](https://github.com/user-attachments/assets/02ea449f-9289-4e5c-97db-32812912c984)

**Comment by Oostjoost** [comment]
![image](https://github.com/user-attachments/assets/42c93d85-3f0f-4923-9c95-3f525215b383)
Hekwerk duidelijk en in het zwart zichtbaar op de print. Zijn er misschien andere instellingen en kleuren in de database ingesteld bij de regio's waar deze grijs getoond wordt?
